package advent2020;

import org.junit.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Day6Test {

    private String sample = "abc\n" +
            "\n" +
            "a\n" +
            "b\n" +
            "c\n" +
            "\n" +
            "ab\n" +
            "ac\n" +
            "\n" +
            "a\n" +
            "a\n" +
            "a\n" +
            "a\n" +
            "\n" +
            "b";

    private int questionSum(String input) {
        int total = 0;
        List<String> answers = new ArrayList<>();
        for (String s : input.split("\n")) {
            if (s.equalsIgnoreCase("")) {
                total += answers.size();
                answers.clear();
                continue;
            }
            for (String i : s.split("")) {
                if (!answers.contains(i)) {
                    answers.add(i);
                }
            }
        }
        total += answers.size();
        answers.clear();
        return total;
    }

    private int questionSumAll(String input) {
        int total = 0;
        boolean start = true;
        List<String> answers = new ArrayList<>();
        for (String s : input.split("\n")) {
            if (s.equalsIgnoreCase("")) {
                total += answers.size();
                answers.clear();
                start = true;
                continue;
            }
            answers = checkAnswers(answers, s, start);
            start = false;
        }
        total += answers.size();
        answers.clear();
        return total;
    }

    private List<String> checkAnswers(List<String> answers, String input, boolean start) {
        if (start) {
            answers.addAll(Arrays.asList(input.split("")));
        } else {
            List<String> compareList = new ArrayList<>();
            for (String s : input.split("")) {
                if (answers.contains(s)) {
                    compareList.add(s);
                }
            }
            if (!compareList.isEmpty()) {
                answers.removeIf(s -> !compareList.contains(s));
            } else {
                answers.clear();
            }
        }
        return answers;
    }

    @Test
    public void test() {
        System.out.println(questionSum(input));
        System.out.println(questionSumAll(input));
    }

    private String input = "ybcgtxznorvjel\n" +
            "brlyvoexnjtgcz\n" +
            "lnbgtxvoiyecjrz\n" +
            "\n" +
            "lcajnyxgzqwim\n" +
            "qznygxmlvwja\n" +
            "gmjzynxaqwls\n" +
            "\n" +
            "cmljinrupeykatzdsfox\n" +
            "ugwqhknvb\n" +
            "\n" +
            "gsdqbrnhotmfwivl\n" +
            "prozsgfwnthvmiq\n" +
            "\n" +
            "vsjpurgokf\n" +
            "dfxpqzabeulknwmjvcsr\n" +
            "pfuvstryihjk\n" +
            "\n" +
            "islxfdrtvzwkyoguh\n" +
            "ogylskzvuftqhirxbdw\n" +
            "fkrtgsxudhioylznvw\n" +
            "\n" +
            "c\n" +
            "c\n" +
            "\n" +
            "uvwigmrlpbqh\n" +
            "qvgriwlbmhpz\n" +
            "nhlsptgbvwimrq\n" +
            "\n" +
            "izhmeksc\n" +
            "zarebypguktc\n" +
            "fzxkveoc\n" +
            "hzcneqkl\n" +
            "\n" +
            "wsaklcyumfjgxpe\n" +
            "gjlueyimxawpkoscf\n" +
            "tgpaeywujxkslmf\n" +
            "\n" +
            "uzxkhngrtem\n" +
            "heumxtrkzgj\n" +
            "kzxtqvehmfyurdgi\n" +
            "xmhtzrukeg\n" +
            "tkhgujzmxenr\n" +
            "\n" +
            "veaxitpwqlkmfcdgu\n" +
            "tuylgfjb\n" +
            "ftuglh\n" +
            "\n" +
            "uqnklfemcd\n" +
            "fueknldq\n" +
            "eqkfdhnmtl\n" +
            "opyelgnqdfkxw\n" +
            "qzkslfden\n" +
            "\n" +
            "q\n" +
            "bu\n" +
            "k\n" +
            "q\n" +
            "\n" +
            "wqeaklcysthvrb\n" +
            "srhcatklwbqyev\n" +
            "ylrqbthswkceva\n" +
            "tsbryhlavcwekq\n" +
            "aketrswybhvlqc\n" +
            "\n" +
            "tyd\n" +
            "ymt\n" +
            "yvt\n" +
            "\n" +
            "hwvclzeby\n" +
            "vywecbhl\n" +
            "wecyqsohlvb\n" +
            "cvlwheyb\n" +
            "blyvewhgc\n" +
            "\n" +
            "wieapdrco\n" +
            "edicwpa\n" +
            "cpdwia\n" +
            "hdwgyvpica\n" +
            "\n" +
            "jvy\n" +
            "fjv\n" +
            "vj\n" +
            "vjf\n" +
            "\n" +
            "czdf\n" +
            "dfzc\n" +
            "dczf\n" +
            "\n" +
            "gpmrwtuoy\n" +
            "tymroagbipw\n" +
            "wombgpcyktr\n" +
            "dtrlongqypmwhsjvfxz\n" +
            "gmrwpyto\n" +
            "\n" +
            "ocnmpvjx\n" +
            "pvjxcm\n" +
            "bmyjrgvxpkc\n" +
            "\n" +
            "jeygorhmxiak\n" +
            "hxifjagoemr\n" +
            "\n" +
            "ncjziqtmpawdufxye\n" +
            "eubydnxpatfwjzkcm\n" +
            "\n" +
            "abmysdl\n" +
            "cpqbifaynmdsl\n" +
            "mjsbdyla\n" +
            "mrdbvjswyal\n" +
            "bvsladmy\n" +
            "\n" +
            "qafokiv\n" +
            "oqhaik\n" +
            "oqmkifa\n" +
            "qaligznro\n" +
            "\n" +
            "aiblwmouqx\n" +
            "mqwbaxolui\n" +
            "oxuibwlmaq\n" +
            "\n" +
            "zvefqkjusco\n" +
            "xuewoskj\n" +
            "kuzfqjsoe\n" +
            "puankilsjodbre\n" +
            "kutoqsjefh\n" +
            "\n" +
            "celsgxhzpjrodmitfukvn\n" +
            "ejkrmnpsgfxvoaihulcz\n" +
            "zuimrfyohspkjvcxelgn\n" +
            "\n" +
            "lbrxfchematouyniw\n" +
            "labiudxyoenh\n" +
            "ikelubxgaoynhz\n" +
            "jnahsdibeuxylov\n" +
            "xovbhaiunlsey\n" +
            "\n" +
            "ipsrknazqblw\n" +
            "dgxutyvejmfc\n" +
            "\n" +
            "sxizpwamjhn\n" +
            "imhnzxawsjp\n" +
            "ahnpswxmizj\n" +
            "wmisxanjzhp\n" +
            "\n" +
            "gtbhymj\n" +
            "zawfkbsiud\n" +
            "\n" +
            "gylpjarczexv\n" +
            "zyajpvoecrlgx\n" +
            "kzrlojeayxgvp\n" +
            "veztfaypxqrljg\n" +
            "\n" +
            "xfivwhodjknmzauqcletpygb\n" +
            "hypeczniafgkoqultxvbdwjm\n" +
            "qxfhjptgnlkvycoudwmizaeb\n" +
            "jizanpbfcyuetmqokhlwvxdg\n" +
            "gjwtexvdfpuamiconybzhlqk\n" +
            "\n" +
            "tvy\n" +
            "yv\n" +
            "yiv\n" +
            "yv\n" +
            "yv\n" +
            "\n" +
            "whueklivtpca\n" +
            "iplkuahwe\n" +
            "tlsekhiuwap\n" +
            "mizpgjwlbahuekr\n" +
            "\n" +
            "mdp\n" +
            "mdp\n" +
            "mpd\n" +
            "pdm\n" +
            "\n" +
            "xjnhkvoewc\n" +
            "osfjprwxhcieavkd\n" +
            "hqjxwkvonec\n" +
            "jlgxctoqhevwkn\n" +
            "kzvjhyxweco\n" +
            "\n" +
            "yk\n" +
            "yk\n" +
            "\n" +
            "hdnxtrvyeiwam\n" +
            "asrwvdhmxeycint\n" +
            "vwxptebdzyioagqmhr\n" +
            "\n" +
            "tfczy\n" +
            "ctyfn\n" +
            "tycf\n" +
            "cwytf\n" +
            "ytfc\n" +
            "\n" +
            "rmtbfezuojpa\n" +
            "utbjepomarzf\n" +
            "rbatejfumpzo\n" +
            "frtuoepamzbj\n" +
            "faejrztmbpuo\n" +
            "\n" +
            "afenbkzjyugowxcpvr\n" +
            "wouafcenbpjvkygzxr\n" +
            "gvneprcbujxzayokfw\n" +
            "vzyparnkxcgbfwouej\n" +
            "ubzxvkrcgnjeapfowy\n" +
            "\n" +
            "vwuqrecngfdlk\n" +
            "lkrnvqgufwdc\n" +
            "wrnldgkqvcfeu\n" +
            "cuwnbgvqfdrkl\n" +
            "\n" +
            "xbh\n" +
            "vacqro\n" +
            "snxumhe\n" +
            "\n" +
            "gxlf\n" +
            "fglx\n" +
            "gxfl\n" +
            "xlgf\n" +
            "lfxg\n" +
            "\n" +
            "uzlryvkmdbweqjocatxnhi\n" +
            "lzjedxqowyhmnabkiufvcrt\n" +
            "ntkrmlwcqdbzaxejyuhvoi\n" +
            "\n" +
            "fbns\n" +
            "nbf\n" +
            "nabylt\n" +
            "\n" +
            "arsif\n" +
            "qzorln\n" +
            "apb\n" +
            "gcvyuhxtkwe\n" +
            "jm\n" +
            "\n" +
            "svu\n" +
            "uvz\n" +
            "pvuf\n" +
            "ucv\n" +
            "\n" +
            "hpjfklnwizys\n" +
            "pzrcfhyslkiqwn\n" +
            "zskfylihnpow\n" +
            "wgfbdkszlypeihn\n" +
            "\n" +
            "vkmcijegnxar\n" +
            "bvknimxrejcga\n" +
            "vegkjcxniram\n" +
            "egkjvmxciran\n" +
            "akgixcjrnemv\n" +
            "\n" +
            "ewixgnuavo\n" +
            "unoeayxkgi\n" +
            "yeiaucxnm\n" +
            "ixaekznu\n" +
            "ajulsenirbqtfhxpd\n" +
            "\n" +
            "frqlmnxdbgewzo\n" +
            "rdtmqlzovkbuncj\n" +
            "qmzxrndoeiyflb\n" +
            "\n" +
            "ukpnyzjiohf\n" +
            "gjfpkinzuoy\n" +
            "ygjozinfupk\n" +
            "iyvjpeozkfnu\n" +
            "kiupfhoyjngzs\n" +
            "\n" +
            "hrpwvsugjafeoyd\n" +
            "djawruhovfezcb\n" +
            "\n" +
            "cepdjoqftlbanyzxgh\n" +
            "cgnayjbfxzeophtdq\n" +
            "\n" +
            "xqg\n" +
            "halqr\n" +
            "qub\n" +
            "qub\n" +
            "\n" +
            "po\n" +
            "ldjb\n" +
            "\n" +
            "zxnqu\n" +
            "zduxsbq\n" +
            "nzuqxgf\n" +
            "niqzxu\n" +
            "zquxl\n" +
            "\n" +
            "qn\n" +
            "ev\n" +
            "cz\n" +
            "bmwjfhlg\n" +
            "\n" +
            "kpfrostvwjqzd\n" +
            "ukbsrjpdzfcowq\n" +
            "\n" +
            "yjtl\n" +
            "jytl\n" +
            "ltyjz\n" +
            "yltj\n" +
            "\n" +
            "dwty\n" +
            "djsct\n" +
            "gtdj\n" +
            "\n" +
            "hoj\n" +
            "jyho\n" +
            "jhos\n" +
            "ojh\n" +
            "\n" +
            "eupzntdmk\n" +
            "pulhzta\n" +
            "\n" +
            "vdfuricnlkjq\n" +
            "cdufvkijqrn\n" +
            "fkdrpnjcuviq\n" +
            "qnfvjudcirk\n" +
            "drijcfkuqvn\n" +
            "\n" +
            "nvbldpqsx\n" +
            "wbdzhqp\n" +
            "iamjtyfg\n" +
            "\n" +
            "iwqexpmtoadjvryuzshk\n" +
            "twzoyhjukxmqsreaipvd\n" +
            "umryqtvxsdpziohaejkw\n" +
            "eruvdmyzapthwqixjkos\n" +
            "\n" +
            "wtgkdqunxroablp\n" +
            "uqmljdantokrpwxg\n" +
            "nkoupqzlgxwdat\n" +
            "\n" +
            "vepioalcghjydn\n" +
            "zutlfxvorkn\n" +
            "qbvnlo\n" +
            "\n" +
            "lmie\n" +
            "ebim\n" +
            "ykmhei\n" +
            "smie\n" +
            "msbeic\n" +
            "\n" +
            "segdzmcnijfpy\n" +
            "pmngjzisdcey\n" +
            "daumgeznqikljcyp\n" +
            "\n" +
            "hocwkeizbmvgnsd\n" +
            "jfirpydx\n" +
            "itqjdyl\n" +
            "\n" +
            "dbwtrzqo\n" +
            "bwdztr\n" +
            "pwbdtzr\n" +
            "wrtbdz\n" +
            "\n" +
            "tcl\n" +
            "ctl\n" +
            "\n" +
            "izfnvwsygkjp\n" +
            "nkfpvyzsgij\n" +
            "ygjvfipksnz\n" +
            "kvpgjysnfzi\n" +
            "jxiboavkfnzgpsy\n" +
            "\n" +
            "gxulavdzi\n" +
            "xeorucjdlym\n" +
            "\n" +
            "hfc\n" +
            "cfh\n" +
            "\n" +
            "oaixdvhwf\n" +
            "kuivdwfxzha\n" +
            "\n" +
            "jsxny\n" +
            "ynsxj\n" +
            "yjxsn\n" +
            "nxsyj\n" +
            "xysnj\n" +
            "\n" +
            "usnjaimqdl\n" +
            "dnuxgy\n" +
            "hdnpcugz\n" +
            "\n" +
            "ejofu\n" +
            "ufe\n" +
            "uef\n" +
            "feu\n" +
            "\n" +
            "defovtzlc\n" +
            "avocyzft\n" +
            "zxwcvftb\n" +
            "\n" +
            "cbga\n" +
            "vgb\n" +
            "\n" +
            "rac\n" +
            "a\n" +
            "jgzaxotn\n" +
            "av\n" +
            "\n" +
            "ugnotpd\n" +
            "ntugodpx\n" +
            "pudgomt\n" +
            "tdislogp\n" +
            "\n" +
            "filsprncvbdamgozwuh\n" +
            "fzqucamrswpihvdlgob\n" +
            "\n" +
            "keaqcjtmzwipdyonvufsl\n" +
            "voysnkmwlzqpfeguiacdtj\n" +
            "ndacvykmeozbsuwpiftlq\n" +
            "wodcqfputzknsyevilma\n" +
            "\n" +
            "aobpjhfwndq\n" +
            "wnbjofqdpah\n" +
            "fnwqdcgxphabj\n" +
            "wadfqbhinjp\n" +
            "\n" +
            "dfegup\n" +
            "pdgyu\n" +
            "\n" +
            "qmdthgnfsoacekpjr\n" +
            "zwqjois\n" +
            "\n" +
            "cuqwdn\n" +
            "cdnwi\n" +
            "cwyvd\n" +
            "tokwjdsxcr\n" +
            "\n" +
            "hlbrqytujx\n" +
            "fdcxlwjquyznksv\n" +
            "wyupmxqjfilsk\n" +
            "\n" +
            "hkrsp\n" +
            "yhwpsrk\n" +
            "krhsp\n" +
            "gorspkh\n" +
            "\n" +
            "kdnsfavte\n" +
            "snadektv\n" +
            "namkstved\n" +
            "etavlknds\n" +
            "esdatkvn\n" +
            "\n" +
            "zbvuponkx\n" +
            "zkjybcanxi\n" +
            "xbunzkv\n" +
            "\n" +
            "sixh\n" +
            "xbgha\n" +
            "\n" +
            "uxfay\n" +
            "urqibka\n" +
            "uao\n" +
            "\n" +
            "lsjkxqirzbcw\n" +
            "sqkbzwjclixr\n" +
            "qsclikrzhxwb\n" +
            "\n" +
            "ozldp\n" +
            "dlpz\n" +
            "dztglp\n" +
            "\n" +
            "rl\n" +
            "lr\n" +
            "lr\n" +
            "\n" +
            "xchdwlniyzjvfskqgu\n" +
            "jczdgywxisl\n" +
            "jxyspdclgizmw\n" +
            "\n" +
            "dblfawuprytvz\n" +
            "mceiqnsxkgltp\n" +
            "pmcxtohlg\n" +
            "\n" +
            "s\n" +
            "s\n" +
            "r\n" +
            "zdkl\n" +
            "\n" +
            "xsftzi\n" +
            "rhmvobe\n" +
            "gitkn\n" +
            "ucgzt\n" +
            "\n" +
            "zfboewhsdi\n" +
            "sfozwbdhie\n" +
            "\n" +
            "iulc\n" +
            "cilu\n" +
            "iluc\n" +
            "ucli\n" +
            "\n" +
            "orlegwpi\n" +
            "polwidg\n" +
            "pomlwiy\n" +
            "\n" +
            "wuzngeba\n" +
            "bnazuce\n" +
            "ubzane\n" +
            "\n" +
            "vywm\n" +
            "ym\n" +
            "\n" +
            "nfmsueclkpqgwai\n" +
            "utlevwmrcxosqkpd\n" +
            "\n" +
            "stkubmdgxnprayjvihocf\n" +
            "jdnhiurkyopfsbmagxtezcv\n" +
            "fokmgyscrpijnbhxtudav\n" +
            "caogfvytximuhrjdpbnsk\n" +
            "\n" +
            "rsabjcmtdwynx\n" +
            "bficzdrnlsjouhta\n" +
            "\n" +
            "mw\n" +
            "wm\n" +
            "mw\n" +
            "\n" +
            "iebmfugxoyqlrpcvjztkwdnh\n" +
            "pelfsdutxqcymaozjhnr\n" +
            "\n" +
            "pebjavucfqyrdzgml\n" +
            "cbzypflawgmjuvredq\n" +
            "yzrujflgcqebvdapm\n" +
            "gbfuqznldejsyvparmc\n" +
            "jcaqeuwvplbfgdmryz\n" +
            "\n" +
            "hkg\n" +
            "xelcms\n" +
            "f\n" +
            "\n" +
            "lihonytfdumjsewrzabpc\n" +
            "hlpcdubrwoazsfmiynetj\n" +
            "owuibptxmdhzyrecsfan\n" +
            "\n" +
            "riosndbpujgcwethz\n" +
            "hwfrzietbougpsdqjn\n" +
            "drntjpzeguiowshb\n" +
            "pwubneoztjsgdhri\n" +
            "rezkbtghcjwdoinspu\n" +
            "\n" +
            "njsa\n" +
            "u\n" +
            "fb\n" +
            "\n" +
            "sfx\n" +
            "s\n" +
            "s\n" +
            "\n" +
            "ucqsmn\n" +
            "istuq\n" +
            "\n" +
            "ingklxq\n" +
            "cnoekp\n" +
            "\n" +
            "jlygxaiwrpdfnheouvc\n" +
            "dvfaingtxwpkozjhylercu\n" +
            "pigfacjweynhuovxlrd\n" +
            "\n" +
            "vpxbtozuemlny\n" +
            "jkgymlvebinctudpxa\n" +
            "byzxemqvtulpn\n" +
            "ytvunxzwqblepm\n" +
            "\n" +
            "jfbkglhtpqudix\n" +
            "grnicbtpqzdxv\n" +
            "\n" +
            "bfokwpmzhtlgquaiejr\n" +
            "iawgbmqvzleoxrhtfpu\n" +
            "zwompxutlbhaifseqrg\n" +
            "xpbqhitclyzrunwodgfesma\n" +
            "\n" +
            "q\n" +
            "qg\n" +
            "q\n" +
            "vq\n" +
            "q\n" +
            "\n" +
            "ekipdozabfsxvugqltjwyrc\n" +
            "dztsokinlyrfxceqjwuavpbg\n" +
            "\n" +
            "eqnkifs\n" +
            "ifqknes\n" +
            "\n" +
            "laecqkp\n" +
            "pugqayce\n" +
            "elcxpraqoj\n" +
            "pecqvfwa\n" +
            "qcepljak\n" +
            "\n" +
            "arnb\n" +
            "qnab\n" +
            "nbaq\n" +
            "dnbaomv\n" +
            "\n" +
            "cbormguajxfiplwvts\n" +
            "dxifemjgwzrobtlpcqvua\n" +
            "aofmcpilxjvbguwtr\n" +
            "\n" +
            "umvdxnwzfqapk\n" +
            "pwuqfzadjmne\n" +
            "uzqpmfyacdw\n" +
            "\n" +
            "mhaeksjiqb\n" +
            "bfqjokusih\n" +
            "jgklnsivbywdc\n" +
            "sxpkfirjomqb\n" +
            "\n" +
            "nhzaplu\n" +
            "ahkipmvo\n" +
            "brtjwg\n" +
            "\n" +
            "mkjxlagycu\n" +
            "uckjxlgma\n" +
            "kjcuxmgal\n" +
            "\n" +
            "ve\n" +
            "ve\n" +
            "\n" +
            "jvkobmcq\n" +
            "gjmqkobc\n" +
            "qjbomcwk\n" +
            "cybojqmk\n" +
            "mjbqocfk\n" +
            "\n" +
            "ducqha\n" +
            "qdlhac\n" +
            "\n" +
            "wlfkid\n" +
            "hipcfkwdlryb\n" +
            "fwlkdi\n" +
            "kdifwvl\n" +
            "\n" +
            "ezs\n" +
            "sze\n" +
            "esz\n" +
            "zes\n" +
            "esz\n" +
            "\n" +
            "hz\n" +
            "utfzphv\n" +
            "ahzgk\n" +
            "shz\n" +
            "\n" +
            "jxclzr\n" +
            "rwfjmu\n" +
            "jro\n" +
            "ojrlny\n" +
            "\n" +
            "topn\n" +
            "wbcojtesg\n" +
            "yrdlqhfz\n" +
            "\n" +
            "wktxsnufbhygzraijlcoed\n" +
            "ciokuzgyrsenbaxhdwjft\n" +
            "nszoywipjhrfxgqbdaeutc\n" +
            "tcxzrysbfuieaovndhwj\n" +
            "bkyouicwtfzlxshjaednr\n" +
            "\n" +
            "aoylnseditpgum\n" +
            "ounmkyzedplaibqs\n" +
            "\n" +
            "fahocyurtgvbsq\n" +
            "byufcgohqvatr\n" +
            "guvoyqthcrbdfa\n" +
            "cbfhayvqrugto\n" +
            "\n" +
            "dgil\n" +
            "dig\n" +
            "idg\n" +
            "apdgi\n" +
            "dig\n" +
            "\n" +
            "rfzmeoyuq\n" +
            "remzyhbip\n" +
            "xtvrykdsancjzmw\n" +
            "pzryfugom\n" +
            "eryomgzlh\n" +
            "\n" +
            "ro\n" +
            "or\n" +
            "ro\n" +
            "doar\n" +
            "rpo\n" +
            "\n" +
            "tbomqznewpgu\n" +
            "zpwbegtquonm\n" +
            "gbunzwtqpmeo\n" +
            "pmnobqtewzgu\n" +
            "\n" +
            "tzkielrca\n" +
            "pwgouhfjvdybsnqm\n" +
            "\n" +
            "bqxr\n" +
            "om\n" +
            "\n" +
            "fkvlmqye\n" +
            "bnqlyda\n" +
            "yojczstxupq\n" +
            "qiye\n" +
            "\n" +
            "wcdl\n" +
            "wcld\n" +
            "lwcd\n" +
            "wdcl\n" +
            "\n" +
            "udx\n" +
            "suhx\n" +
            "\n" +
            "ypmrvaj\n" +
            "aphrjxowvyz\n" +
            "jarvpmq\n" +
            "vpcwarbj\n" +
            "tugveaprjsn\n" +
            "\n" +
            "cubgyqflopxnj\n" +
            "apnxvc\n" +
            "\n" +
            "c\n" +
            "c\n" +
            "c\n" +
            "c\n" +
            "c\n" +
            "\n" +
            "ykdeblvoijpqtns\n" +
            "sbnoigt\n" +
            "nbmitoxas\n" +
            "ibosnxt\n" +
            "\n" +
            "klbdfgmo\n" +
            "va\n" +
            "ylcu\n" +
            "\n" +
            "sgdrutfcbwxleyvmqjoz\n" +
            "hztjqbduiefkvxwcygmolr\n" +
            "eymudvjwlqcxrzfgtob\n" +
            "\n" +
            "jcghosr\n" +
            "jpagrmecsho\n" +
            "\n" +
            "xtlgomkfpciezyq\n" +
            "ylrgtxmchkq\n" +
            "dgtlkwymvxnqc\n" +
            "cgxalbkydwsjmqt\n" +
            "\n" +
            "lvg\n" +
            "vg\n" +
            "vjgka\n" +
            "\n" +
            "xulzdqyef\n" +
            "xuezfldyq\n" +
            "zduyfqexl\n" +
            "lqfezuydx\n" +
            "\n" +
            "afpboknehzmculswdyjqix\n" +
            "winjabfuyedmzoshxlcqpk\n" +
            "smnaybfjzkowdpleiuchqx\n" +
            "bqsuknafemzvpljihwycdox\n" +
            "\n" +
            "huvrzdawnce\n" +
            "irvodxzmnksq\n" +
            "tvrdneazfcu\n" +
            "nldygvuezr\n" +
            "\n" +
            "ifwousayrbjvxcpld\n" +
            "ugrnfjhvbcoatspxk\n" +
            "vsiobyrcpjdfzuaxq\n" +
            "\n" +
            "ubeisxaw\n" +
            "klqn\n" +
            "ok\n" +
            "rmf\n" +
            "n\n" +
            "\n" +
            "j\n" +
            "grpy\n" +
            "mnwf\n" +
            "\n" +
            "yrsnckxbuvhdtmgeqapj\n" +
            "asjkxuymdbrlechvqotngp\n" +
            "adrjpnbhmutgkxecyvqsi\n" +
            "\n" +
            "agtlryz\n" +
            "pywxhgqu\n" +
            "okyghqduj\n" +
            "mbycgvhjq\n" +
            "\n" +
            "aihswznpod\n" +
            "bdaezc\n" +
            "\n" +
            "grdiok\n" +
            "dtkoxqrnl\n" +
            "\n" +
            "vqjpfiembrcyohxlgdts\n" +
            "uhvgxiceoyafmtpqs\n" +
            "gqpcfextaviomwhys\n" +
            "voygtpxhmiqcfse\n" +
            "\n" +
            "alv\n" +
            "xohjegy\n" +
            "\n" +
            "k\n" +
            "z\n" +
            "h\n" +
            "\n" +
            "wdoc\n" +
            "dwco\n" +
            "domcw\n" +
            "\n" +
            "pencwlstgb\n" +
            "toapxnsye\n" +
            "taehsxpjn\n" +
            "\n" +
            "unhav\n" +
            "dbslritz\n" +
            "eucw\n" +
            "ekv\n" +
            "eag\n" +
            "\n" +
            "fewghvcj\n" +
            "hcejwfvg\n" +
            "jgxwfvclheu\n" +
            "ewjfzvghc\n" +
            "ehfcgjwv\n" +
            "\n" +
            "moaclkpxythqvesdgzuwib\n" +
            "nrvlkyaiuhwsxfjzeoqmdb\n" +
            "\n" +
            "hda\n" +
            "dah\n" +
            "dha\n" +
            "dha\n" +
            "dha\n" +
            "\n" +
            "kgu\n" +
            "efntky\n" +
            "liw\n" +
            "zyh\n" +
            "\n" +
            "zqtohusn\n" +
            "jmuhq\n" +
            "lxqvkruhciwey\n" +
            "mjqthzanbu\n" +
            "\n" +
            "ljtief\n" +
            "lijeft\n" +
            "jlteif\n" +
            "fiejlbt\n" +
            "fjtlie\n" +
            "\n" +
            "qdxygilu\n" +
            "tldagovk\n" +
            "npmdckoaltg\n" +
            "\n" +
            "i\n" +
            "i\n" +
            "i\n" +
            "i\n" +
            "i\n" +
            "\n" +
            "wk\n" +
            "dal\n" +
            "uzmbsen\n" +
            "k\n" +
            "\n" +
            "cqlxwzvetfakbidmgoujhs\n" +
            "afzghkswqibynljtoecvrx\n" +
            "swzkjhatgqvblxfneoci\n" +
            "\n" +
            "h\n" +
            "on\n" +
            "h\n" +
            "h\n" +
            "\n" +
            "fzvckrajbeso\n" +
            "ejrcfnsxv\n" +
            "tlupewdmcirygv\n" +
            "vjqrec\n" +
            "\n" +
            "hadxcqevfmr\n" +
            "hxdarvmfcqe\n" +
            "chdvexqmfr\n" +
            "vrhmxecq\n" +
            "ehoxqnrcumv\n" +
            "\n" +
            "wkdtuyegzqichna\n" +
            "uihqapcwdmteznykg\n" +
            "tnjrqcydihfgvwzbseuak\n" +
            "dagetcyqizhnuwk\n" +
            "\n" +
            "jie\n" +
            "bei\n" +
            "ei\n" +
            "eji\n" +
            "\n" +
            "td\n" +
            "t\n" +
            "t\n" +
            "t\n" +
            "\n" +
            "dbqvtxjeranwmofhigc\n" +
            "mtgcdevirwahnxjoqbf\n" +
            "cftanqvibjmhxgowyred\n" +
            "\n" +
            "iqgphzrawkevmjfds\n" +
            "jhifptdmra\n" +
            "jdxaobfypmnhirc\n" +
            "xtdamplhrfibj\n" +
            "\n" +
            "majypozns\n" +
            "pomjzusayn\n" +
            "zmspayjon\n" +
            "mjnzoaspy\n" +
            "\n" +
            "puvwane\n" +
            "avwpnue\n" +
            "ewvaun\n" +
            "dauqnevw\n" +
            "\n" +
            "jsvcumahzqktyp\n" +
            "obifedg\n" +
            "wnolrxg\n" +
            "\n" +
            "ewgot\n" +
            "odycnb\n" +
            "tjgwo\n" +
            "\n" +
            "di\n" +
            "id\n" +
            "id\n" +
            "di\n" +
            "idcw\n" +
            "\n" +
            "itovydpksgxmblqhun\n" +
            "ogxaiurvmhlsfwdbpzcy\n" +
            "gdemlsyaijofbpuvxhz\n" +
            "\n" +
            "kwdqozmvuegtsrxi\n" +
            "uyetkxigdwosq\n" +
            "\n" +
            "cw\n" +
            "cw\n" +
            "cw\n" +
            "\n" +
            "aoh\n" +
            "ano\n" +
            "\n" +
            "rnywdtil\n" +
            "dpvhtrf\n" +
            "tgblnpd\n" +
            "keactdx\n" +
            "tgrdzos\n" +
            "\n" +
            "mfip\n" +
            "impf\n" +
            "fmpi\n" +
            "impf\n" +
            "imfp\n" +
            "\n" +
            "kqpvbyjnewx\n" +
            "ywjxpknqzeb\n" +
            "nqeukpjbwxy\n" +
            "penxzqbjykw\n" +
            "\n" +
            "zpyjigfcuxdktarq\n" +
            "yapfiqrtdkcgjx\n" +
            "aepjcrbgyxftikdq\n" +
            "jptaiqdcykxrgf\n" +
            "\n" +
            "ftwedcvib\n" +
            "btcdfewl\n" +
            "ivdfwbtce\n" +
            "ftcdxeqbkwu\n" +
            "bvfeitwcd\n" +
            "\n" +
            "uiqj\n" +
            "qi\n" +
            "\n" +
            "oxghqnsd\n" +
            "udygoh\n" +
            "hdoxg\n" +
            "rpafchvogd\n" +
            "\n" +
            "hpbytijfwx\n" +
            "jywtpixhbsf\n" +
            "pwhyfjbxiqt\n" +
            "qtipwfjxbhy\n" +
            "xqhfbptywij\n" +
            "\n" +
            "dfslmxhie\n" +
            "smzwlfqehi\n" +
            "\n" +
            "kpr\n" +
            "stcve\n" +
            "\n" +
            "irt\n" +
            "rti\n" +
            "irt\n" +
            "rti\n" +
            "\n" +
            "bunl\n" +
            "nlb\n" +
            "lprhdby\n" +
            "\n" +
            "bo\n" +
            "ob\n" +
            "ob\n" +
            "\n" +
            "bowdlaegtqypmiz\n" +
            "wonjglmdyapqhike\n" +
            "\n" +
            "akwfdicyteo\n" +
            "kaoewyidtcf\n" +
            "wyafoeitckd\n" +
            "ctwaifokeyd\n" +
            "\n" +
            "usikpnl\n" +
            "plunkis\n" +
            "nliskuwp\n" +
            "upisnkl\n" +
            "alinspukr\n" +
            "\n" +
            "fmosyehatupnxcrbl\n" +
            "zmtfcoghsperajnbylxu\n" +
            "ltnfweypcbmarosxhu\n" +
            "fuabtspeojcrhknlmyx\n" +
            "pcmdlsoxrytevqfnbuahi\n" +
            "\n" +
            "tpjvhomdzurfsbqgxieynw\n" +
            "deopwshxkgtibylnzqmrfujv\n" +
            "bpxszafutyhgdenwvmqijro\n" +
            "ixtjfrpbozsngqwmduhyve\n" +
            "elfvxrhspguyinzjwtmbodq\n" +
            "\n" +
            "kvgqfjtzonx\n" +
            "lptjicfezk\n" +
            "tbxkfjmvz\n" +
            "\n" +
            "d\n" +
            "q\n" +
            "d\n" +
            "rg\n" +
            "\n" +
            "gvnmslbrqduhipyx\n" +
            "sygxvmblqrjhipau\n" +
            "ufirbqgpvhsklxmy\n" +
            "bhrpgqxmivyulzs\n" +
            "\n" +
            "mdfikeywgxsqlbn\n" +
            "ilqgnfbdkexymsw\n" +
            "mynqlfgeidbkxws\n" +
            "kndefxlymisbgqw\n" +
            "bmgfeiwxkndsqly\n" +
            "\n" +
            "firjqazycdmlpebwvkuh\n" +
            "nyopgcvhsxlujedkmfrq\n" +
            "\n" +
            "ctmupagrjydizes\n" +
            "hdqxglckzvabwi\n" +
            "\n" +
            "uogtnvfbwa\n" +
            "qkgxofaeictuvnj\n" +
            "ngfuolytshmvr\n" +
            "\n" +
            "bhgrcpltzvqjwfas\n" +
            "tchsrqzwbpgvafj\n" +
            "wgharjbsptqzfvc\n" +
            "qftchjazrgspbvw\n" +
            "\n" +
            "sbzjewryqhpxcivnk\n" +
            "expnzhsqykirbjcw\n" +
            "oyagjndwhkpxlqbmcrizefs\n" +
            "\n" +
            "sfhpqjndwvb\n" +
            "rjvbwnphsqfedm\n" +
            "ndbphlfwjvqs\n" +
            "\n" +
            "whrefxbvuma\n" +
            "hxmrubvfwea\n" +
            "\n" +
            "t\n" +
            "t\n" +
            "t\n" +
            "\n" +
            "favkeblzcnt\n" +
            "ymcz\n" +
            "xucgdszp\n" +
            "cjzrh\n" +
            "irpqwozc\n" +
            "\n" +
            "my\n" +
            "m\n" +
            "m\n" +
            "\n" +
            "alsknvxifqcpjymrz\n" +
            "fpjcrqzmlyxvsaikn\n" +
            "\n" +
            "yaj\n" +
            "ykanc\n" +
            "atx\n" +
            "\n" +
            "ilupyjozc\n" +
            "zcjbiolu\n" +
            "czjioulsg\n" +
            "cokzbjuil\n" +
            "auvmjzohqrwilc\n" +
            "\n" +
            "wsxunpgv\n" +
            "vgwsu\n" +
            "ugswvq\n" +
            "usafwhvg\n" +
            "gfwuqsv\n" +
            "\n" +
            "s\n" +
            "sw\n" +
            "\n" +
            "wvqdzfolabmirjc\n" +
            "ljwarzcmbfqodiv\n" +
            "aswzbmdjtnlfqovgxc\n" +
            "\n" +
            "znrmjsy\n" +
            "nsjrymz\n" +
            "ymrnzsj\n" +
            "\n" +
            "vpgac\n" +
            "dgjvpcua\n" +
            "vycgpfa\n" +
            "pvcga\n" +
            "rapvcg\n" +
            "\n" +
            "mb\n" +
            "mb\n" +
            "bmnt\n" +
            "bm\n" +
            "\n" +
            "gsnjzuby\n" +
            "wntqv\n" +
            "nhld\n" +
            "\n" +
            "onzrkyudwapxf\n" +
            "dkupywnraxof\n" +
            "\n" +
            "lmst\n" +
            "slmt\n" +
            "tldsmvp\n" +
            "tsmol\n" +
            "sltm\n" +
            "\n" +
            "s\n" +
            "n\n" +
            "\n" +
            "qsagxhkyeinrvb\n" +
            "kiyeqrnbgxvash\n" +
            "syerxqghivnkab\n" +
            "rqkasenivxghyb\n" +
            "\n" +
            "ncfrvqmgkahtpbozdjy\n" +
            "fvdzwkoam\n" +
            "lixodafekmzv\n" +
            "dokuazvfm\n" +
            "zdoakvfms\n" +
            "\n" +
            "vlhbq\n" +
            "ouqvrxhls\n" +
            "sfhqlvx\n" +
            "\n" +
            "qxorudp\n" +
            "peduq\n" +
            "qundp\n" +
            "qdpu\n" +
            "\n" +
            "rhpyabj\n" +
            "brycauhjp\n" +
            "apbhrxyj\n" +
            "\n" +
            "ygk\n" +
            "ktpy\n" +
            "kvyn\n" +
            "yvkn\n" +
            "\n" +
            "xkhagnmpdcv\n" +
            "hjoakl\n" +
            "\n" +
            "dxcjugqvpleairsytkh\n" +
            "rqndpilgchysvoeutxma\n" +
            "\n" +
            "njeikmhawblcdxoygufrpt\n" +
            "gnrxuicweofdtpkjhslamby\n" +
            "perifdanxhwtbzokgumyclj\n" +
            "\n" +
            "ghpdecujkxzltysfbv\n" +
            "xftkvhudgcplyjzesb\n" +
            "cbksuezftdjhwvxgipyl\n" +
            "\n" +
            "wxtz\n" +
            "wztx\n" +
            "\n" +
            "bcva\n" +
            "acvb\n" +
            "avcb\n" +
            "\n" +
            "oydfhxunzaijlpgeqb\n" +
            "qzeafxwrpiycndmogbj\n" +
            "finjbylagzdqxoep\n" +
            "pyqbjondvzgefixa\n" +
            "aonbixfejqdpgzy\n" +
            "\n" +
            "edzm\n" +
            "ejmz\n" +
            "mgliz\n" +
            "\n" +
            "q\n" +
            "qb\n" +
            "yn\n" +
            "glq\n" +
            "fwu\n" +
            "\n" +
            "whbkfvgpmjzdl\n" +
            "gzmvwpjdbltfh\n" +
            "\n" +
            "prkxeaoygt\n" +
            "zfrewaysbtx\n" +
            "\n" +
            "hoytqlezuxdmcnw\n" +
            "zqtyewudcfnomxh\n" +
            "hrxinwocqtdemzu\n" +
            "wzmjhquxdngcpoe\n" +
            "\n" +
            "pnwldbucofxq\n" +
            "nlwbcoqfxpud\n" +
            "icwpxnbodyqmluvf\n" +
            "ozfwdhclupxbqn\n" +
            "dcqonulbwpxf\n" +
            "\n" +
            "ywfjkqrgidnhbuea\n" +
            "aeyidkwghubrjqf\n" +
            "ihjrakdwbuefgqy\n" +
            "irdjgbwfeqaukyh\n" +
            "hyeujqrkiwdagfb\n" +
            "\n" +
            "jstapqk\n" +
            "wmeujqts\n" +
            "utzmwqjs\n" +
            "zxqbmstj\n" +
            "yrsthdignvqj\n" +
            "\n" +
            "yva\n" +
            "actvy\n" +
            "\n" +
            "okqvf\n" +
            "mfok\n" +
            "akfno\n" +
            "oakvf\n" +
            "\n" +
            "cdfugre\n" +
            "gedfucr\n" +
            "dfcerug\n" +
            "\n" +
            "ingczmjrfp\n" +
            "pmcfrgnijz\n" +
            "mepzjirfcgn\n" +
            "zsnmhpfguwircjq\n" +
            "\n" +
            "dpw\n" +
            "zlpwd\n" +
            "pwd\n" +
            "dpw\n" +
            "\n" +
            "wbzluvga\n" +
            "yiupsdj\n" +
            "yfu\n" +
            "ncfou\n" +
            "pfu\n" +
            "\n" +
            "fbxnrjdosah\n" +
            "rnfdasxjbhoz\n" +
            "nohdxufrjkabs\n" +
            "\n" +
            "dfgyeismzkr\n" +
            "nhukvdazrwgqisl\n" +
            "xbzkgsmderi\n" +
            "ksditprgzb\n" +
            "zkdsgir\n" +
            "\n" +
            "gjytlskbrhdcwfq\n" +
            "ljirabqwtygcosuhd\n" +
            "\n" +
            "bk\n" +
            "kbdi\n" +
            "yjk\n" +
            "ik\n" +
            "\n" +
            "ksquemnvtlxofj\n" +
            "xeqoflmadtunsvjkc\n" +
            "jtvnequxslfmok\n" +
            "qvnkmtxosljeuf\n" +
            "\n" +
            "zxqlnj\n" +
            "qzkjl\n" +
            "jqlz\n" +
            "jlqz\n" +
            "qjzl\n" +
            "\n" +
            "jniylks\n" +
            "jiyheksb\n" +
            "jydtiaks\n" +
            "\n" +
            "o\n" +
            "o\n" +
            "h\n" +
            "\n" +
            "e\n" +
            "e\n" +
            "e\n" +
            "e\n" +
            "\n" +
            "hrpgqasc\n" +
            "grpschqa\n" +
            "rzgcsjphq\n" +
            "\n" +
            "ecitkohxdb\n" +
            "okteihdcxb\n" +
            "xobijctedhk\n" +
            "ktboecaixhd\n" +
            "\n" +
            "paubelofzrwmsvhg\n" +
            "pagezysfb\n" +
            "\n" +
            "esgvqfzkijypan\n" +
            "zeivfdksgqapyrjn\n" +
            "\n" +
            "wi\n" +
            "i\n" +
            "inkm\n" +
            "i\n" +
            "\n" +
            "zcun\n" +
            "uc\n" +
            "uc\n" +
            "okcug\n" +
            "\n" +
            "trogu\n" +
            "oyrug\n" +
            "ozgrfuqn\n" +
            "\n" +
            "raj\n" +
            "oz\n" +
            "pbr\n" +
            "\n" +
            "iwhxjelgd\n" +
            "jiwhexldg\n" +
            "hlgjxdwei\n" +
            "jlwxhgeid\n" +
            "xhldjzgwtmief\n" +
            "\n" +
            "kclge\n" +
            "srlkec\n" +
            "kelc\n" +
            "\n" +
            "eofisurvqxh\n" +
            "ukvfrisqxoe\n" +
            "uexrqifsvo\n" +
            "\n" +
            "okdimecwvfuhrljtpxgyanbzqs\n" +
            "xacwijpeqlkbuvdsgofmtnzhyr\n" +
            "\n" +
            "amwgdsovpnryclfeit\n" +
            "rcwyfevgotlidanspm\n" +
            "vtneaoylpdifcrwgsm\n" +
            "tonlrdacsfigpyvewm\n" +
            "pisgdcmtovwfelnyra\n" +
            "\n" +
            "uetxnmzilhksb\n" +
            "kminofleutjwdpz\n" +
            "tmeculxqkzin\n" +
            "kqlimryetnavzu\n" +
            "\n" +
            "cmnjsbqvde\n" +
            "qmzdbnjsv\n" +
            "vngjtmpsbqd\n" +
            "dqnmspbvj\n" +
            "dmsqvjbn\n" +
            "\n" +
            "kgxdn\n" +
            "gxndf\n" +
            "\n" +
            "onpwxkus\n" +
            "sgnpkw\n" +
            "pwnrvks\n" +
            "sknbpwta\n" +
            "wopksn\n" +
            "\n" +
            "gfqylwtcvpjsk\n" +
            "cwvplskgfxty\n" +
            "lkgvywscptf\n" +
            "ogwspvfylktc\n" +
            "\n" +
            "dgbcvjfieurw\n" +
            "iknqeztowur\n" +
            "\n" +
            "fzsar\n" +
            "fno\n" +
            "\n" +
            "jiaxdfroq\n" +
            "rqhxjigaynd\n" +
            "iudjaqrx\n" +
            "qmxardfvji\n" +
            "qxjcdira\n" +
            "\n" +
            "ghfosy\n" +
            "yfgs\n" +
            "hfspb\n" +
            "fucaiq\n" +
            "\n" +
            "ynrbkleixc\n" +
            "sezybviarnl\n" +
            "\n" +
            "ywcanufmveh\n" +
            "vafuecjm\n" +
            "\n" +
            "qcrmvuihkboexdlftp\n" +
            "kufohcswxpearvbyqd\n" +
            "hrnzpkocxfdevqujbs\n" +
            "qoxuhjpfvbckdre\n" +
            "gkdfvpbheqocuxr\n" +
            "\n" +
            "wtk\n" +
            "ktw\n" +
            "\n" +
            "xcadnijfkvqystgluz\n" +
            "kznliathwoxsmvybrgeqf\n" +
            "klzsivxayqnfgut\n" +
            "\n" +
            "clo\n" +
            "lco\n" +
            "ocl\n" +
            "oacql\n" +
            "lco\n" +
            "\n" +
            "iyzkvsdhpngo\n" +
            "remlyvz\n" +
            "\n" +
            "uyzw\n" +
            "zuv\n" +
            "zu\n" +
            "\n" +
            "tq\n" +
            "t\n" +
            "\n" +
            "oeicrl\n" +
            "byxrsfdz\n" +
            "rcjog\n" +
            "cr\n" +
            "irck\n" +
            "\n" +
            "pgistdzl\n" +
            "y\n" +
            "xmq\n" +
            "m\n" +
            "afn\n" +
            "\n" +
            "g\n" +
            "dhg\n" +
            "g\n" +
            "vwg\n" +
            "\n" +
            "nfgtoy\n" +
            "ugyft\n" +
            "tygfo\n" +
            "futyegr\n" +
            "gstlwpkyf\n" +
            "\n" +
            "vn\n" +
            "nmv\n" +
            "vn\n" +
            "nv\n" +
            "nv\n" +
            "\n" +
            "ozivnfbaktuedlrcs\n" +
            "oramfqlcbuswtvdzjni\n" +
            "\n" +
            "jxp\n" +
            "xpj\n" +
            "\n" +
            "mc\n" +
            "wabq\n" +
            "lrgsuezypd\n" +
            "wiv\n" +
            "\n" +
            "eofl\n" +
            "snpkflyqmdzwb\n" +
            "jehlirf\n" +
            "cjflrh\n" +
            "fljc\n" +
            "\n" +
            "ltubcvkymoajwxzsrhndpgf\n" +
            "ogvibsazqtujrdewfxymph\n" +
            "\n" +
            "egdchpsvwjfaqybn\n" +
            "zndqagubwpkscyjh\n" +
            "\n" +
            "wlbjgnopeayszicrmf\n" +
            "nosbgiezpjaywqfmrlc\n" +
            "jgilbrmwosyzcafnep\n" +
            "agycorlqmzweibpjfsn\n" +
            "zjlrpnfbeasidmcgyowt\n" +
            "\n" +
            "vijh\n" +
            "ndsfcamyxz\n" +
            "woujvp\n" +
            "\n" +
            "uhealmbgtyix\n" +
            "zilxmb\n" +
            "pvxlfqmwsidb\n" +
            "\n" +
            "fjmdnvrbg\n" +
            "gdlvuqhkpb\n" +
            "kbczdvgp\n" +
            "\n" +
            "lqkt\n" +
            "tkjqi\n" +
            "\n" +
            "wcrmtpf\n" +
            "bkqws\n" +
            "\n" +
            "ngzltjq\n" +
            "nlkut\n" +
            "iwlrytn\n" +
            "xltsmnu\n" +
            "ztlnacfj\n" +
            "\n" +
            "exfviczl\n" +
            "iczhelxv\n" +
            "zelivxc\n" +
            "vfilzexcp\n" +
            "xlzvfice\n" +
            "\n" +
            "ytgac\n" +
            "tacyk\n" +
            "qacy\n" +
            "candymh\n" +
            "\n" +
            "yrqczhgfovwnisbu\n" +
            "vhlgknps\n" +
            "\n" +
            "sbwugclexy\n" +
            "wbzuhlgsc\n" +
            "umvwiknljcdotbfgs\n" +
            "rluhbcqgsaw\n" +
            "\n" +
            "vymaruskjc\n" +
            "akvrsmjuyc\n" +
            "vrcyuasmbjk\n" +
            "pursajkvycm\n" +
            "czpmyusvajrk\n" +
            "\n" +
            "ofwvqmlr\n" +
            "vmq\n" +
            "vmq\n" +
            "\n" +
            "ysnwieoauzq\n" +
            "nuyqesaowz\n" +
            "yoesanuwqz\n" +
            "kuzgoswayqnle\n" +
            "\n" +
            "eomivztrgn\n" +
            "ivmretong\n" +
            "invkmrge\n" +
            "vnmzegcri\n" +
            "vyrmflsjgiuen\n" +
            "\n" +
            "eqrmyzpvkwfbgtjlxshdoin\n" +
            "gzolfstrvybjeqnmxpikhd\n" +
            "nroxitkevgzmypjdqbsfhl\n" +
            "ofgmtrjilnbekxhsqyzdpv\n" +
            "dhlqnvgsjiyzbkpotxrefm\n" +
            "\n" +
            "hozruskcedfwiaq\n" +
            "coptzfyuvxldrm\n" +
            "\n" +
            "l\n" +
            "l\n" +
            "l\n" +
            "\n" +
            "dyslqoiw\n" +
            "ymjqdi\n" +
            "\n" +
            "syxnhbi\n" +
            "dpkvjr\n" +
            "eukgwozaf\n" +
            "ekjz\n" +
            "\n" +
            "yvwbgqcrotjlnpeha\n" +
            "lhpoetrgabvnqjwy\n" +
            "blgszmfkhyntepwoaixqrvj\n" +
            "byrpjoenhagwtuvql\n" +
            "\n" +
            "z\n" +
            "v\n" +
            "tgy\n" +
            "\n" +
            "d\n" +
            "d\n" +
            "d\n" +
            "d\n" +
            "d\n" +
            "\n" +
            "dc\n" +
            "dca\n" +
            "dc\n" +
            "cd\n" +
            "dcz\n" +
            "\n" +
            "locsfetpwknxbzgvja\n" +
            "jxgnvfzphceiskaotwl\n" +
            "fotrsavxmjyhnwpgzelck\n" +
            "sfvpqhxgyjeonazclmwkt\n" +
            "choefxapjniztgwlvskq\n" +
            "\n" +
            "kbyxoztlp\n" +
            "ilptzojgvnexw\n" +
            "atxmzkolcp\n" +
            "uqkszlopdxt\n" +
            "\n" +
            "zj\n" +
            "ojpz\n" +
            "\n" +
            "khjzinxbsvytagfwrdpclm\n" +
            "gkfnjmrsaxublcov\n" +
            "nxlacsrmgkvbfju\n" +
            "uagsxkrfmbvcjnl\n" +
            "kexajvcfrnlsmgb\n" +
            "\n" +
            "jwstzrmqyg\n" +
            "qiolxndue\n" +
            "\n" +
            "aljc\n" +
            "onxjpaltygwvucz\n" +
            "qacrjls\n" +
            "ajcfhl\n" +
            "ijqralc\n" +
            "\n" +
            "hinlgsoyjrwux\n" +
            "onlujsyxgirwh\n" +
            "\n" +
            "l\n" +
            "l\n" +
            "l\n" +
            "l\n" +
            "l\n" +
            "\n" +
            "eoqhmwpjxdkib\n" +
            "dpewgjm\n" +
            "epjmdw\n" +
            "edpnmjw\n" +
            "pjdewm\n" +
            "\n" +
            "wvhaks\n" +
            "vrgoah\n" +
            "\n" +
            "dvqanm\n" +
            "ladgcypwnmhjz\n" +
            "xsidnmae\n" +
            "fidranekum\n" +
            "datnmb\n" +
            "\n" +
            "vkashdfylrcigpz\n" +
            "fzpsydgrvwcl\n" +
            "kdpglscryfz\n" +
            "sgzqcytfoplebudmxr\n" +
            "ldzsywpjfrgc\n" +
            "\n" +
            "gtme\n" +
            "mgfptwe\n" +
            "tmge\n" +
            "\n" +
            "ameogqc\n" +
            "ogqcema\n" +
            "meocqag\n" +
            "ecmaoqg\n" +
            "oeamicgq\n" +
            "\n" +
            "jg\n" +
            "hgij\n" +
            "fjg\n" +
            "\n" +
            "dgypvjbrik\n" +
            "zriqkvgpdbjaxy\n" +
            "\n" +
            "ezfbiwhrtgl\n" +
            "ozfxebispgdtnv\n" +
            "btegzjafui\n" +
            "\n" +
            "jiabmdnuftcsgqw\n" +
            "kazroxypl\n" +
            "\n" +
            "mqoaxjcuzhngk\n" +
            "jgswxaykfmehvuiqzon\n" +
            "lbuakqzjhdmnxgo\n" +
            "\n" +
            "bacszqyketnvpguofhrwmx\n" +
            "ptszqxamuewikbngyfhvdroc\n" +
            "heqrcosaxtwgbplfnzuvykmj\n" +
            "\n" +
            "knxabluhoyviedjfpsmrqcw\n" +
            "scqixedwvumkoanjbrfyhl\n" +
            "tisjfuywcqnremhobldkaxv\n" +
            "shvojgwydialxekbmcufnrq\n" +
            "\n" +
            "nyxmrhszik\n" +
            "mapcikqstjfrzx\n" +
            "\n" +
            "gdlctrjzek\n" +
            "hjsgkeyr\n" +
            "\n" +
            "qepm\n" +
            "eqlpm\n" +
            "eqmp\n" +
            "mqxepn\n" +
            "pqem\n" +
            "\n" +
            "bvgkrl\n" +
            "vboc\n" +
            "wcbvziu\n" +
            "vqfpdabh\n" +
            "\n" +
            "gpn\n" +
            "ngmpc\n" +
            "\n" +
            "twpvxflgjqoumydkbc\n" +
            "uprelhcmqwdksixynzta\n" +
            "\n" +
            "h\n" +
            "h\n" +
            "\n" +
            "jhnxwesqrpc\n" +
            "vpsgmitbaoyfudjz\n" +
            "\n" +
            "yuwbhtsmjlcqefdv\n" +
            "ebmutvlfcqdsjhy\n" +
            "utswqzjlbvycpadefmh\n" +
            "sejvrxgqdlmbtouyhnfc\n" +
            "zijctvqmlyuahfbsdep\n" +
            "\n" +
            "dflwcg\n" +
            "mrflgw\n" +
            "wfduygl\n" +
            "\n" +
            "ytnlzrju\n" +
            "uvztnjly\n" +
            "zljbryutn\n" +
            "zyjlnut\n" +
            "tljuozyn\n" +
            "\n" +
            "hskjpotzxndciuveygqbf\n" +
            "tovpizqhkfjyxucsgdbne\n" +
            "zchinjfgpxuvqodbtseky\n" +
            "ewpzdvhbgqnkcfujixsoyt\n" +
            "\n" +
            "hwogmrjsanyfkxcuzlqip\n" +
            "zgefdbcrvawhsknxlup\n" +
            "\n" +
            "vpnoqlyctz\n" +
            "lazbrndtc\n" +
            "cbzlduthn\n" +
            "ztnslmcwkegjx\n" +
            "\n" +
            "g\n" +
            "g\n" +
            "g\n" +
            "mg\n" +
            "\n" +
            "scdpkxnwevjzuliaot\n" +
            "ieltzxk\n" +
            "etkilxz\n" +
            "ekrxizlmt\n" +
            "lztxefikb\n" +
            "\n" +
            "fojsglve\n" +
            "\n" +
            "mpdxfg\n" +
            "kfdxma\n" +
            "dkfxavtm\n" +
            "wnbxdmcof\n" +
            "\n" +
            "lsoytwjgnxfpu\n" +
            "jxnluyisgp\n" +
            "jygpxslnmur\n" +
            "npsjlguyx\n" +
            "\n" +
            "rdh\n" +
            "rdh\n" +
            "\n" +
            "apbutxfrwydzin\n" +
            "xrgnqelbdtoczafhjm\n" +
            "drkuztfnxba\n" +
            "\n" +
            "bdmstxhqnrzeyj\n" +
            "fubwrmohipenjclkgya\n" +
            "\n" +
            "usrxcktp\n" +
            "srxotup\n" +
            "rulpxit\n" +
            "euxptrn\n" +
            "\n" +
            "pryjxzemofknaqwh\n" +
            "owzqrhmknsjaedxyfb\n" +
            "ahkijzwfrmqnxolscvey\n" +
            "uqnxfkrwmatcsgeyohjz\n" +
            "\n" +
            "gq\n" +
            "q\n" +
            "q\n" +
            "q\n" +
            "\n" +
            "hbkieng\n" +
            "behdikgm\n" +
            "dkbeygh\n" +
            "ebgshk\n" +
            "\n" +
            "xcdliskjvqhazmgp\n" +
            "zdilgjchpavusmxk\n" +
            "jwxavzlkchdobmgyspi\n" +
            "vijgcxakdhlpqszm\n" +
            "\n" +
            "qkoxgd\n" +
            "zkuxdmbyqcglf\n" +
            "\n" +
            "hjxscnryl\n" +
            "nsmahy\n" +
            "snmhy\n" +
            "ovthdys\n" +
            "\n" +
            "vbwhoizkgsncaqr\n" +
            "waobkhsivcrznjqg\n" +
            "wzsrcgnabkhoqiv\n" +
            "oanbsyrhicgwvzkxq\n" +
            "hurqnbcgovfkawzis\n" +
            "\n" +
            "zxvbs\n" +
            "bdpn\n" +
            "qb\n" +
            "bv\n" +
            "\n" +
            "hdkixlmqovte\n" +
            "ihtrouqdnxlk\n" +
            "ltioudhqkx\n" +
            "bxidhtklufoqw\n" +
            "\n" +
            "s\n" +
            "scvai\n" +
            "s\n" +
            "sb\n" +
            "ws\n" +
            "\n" +
            "uaxeycr\n" +
            "aubsiqxrv\n" +
            "aohrdkxu\n" +
            "reaux\n" +
            "\n" +
            "trcfn\n" +
            "txbgc\n" +
            "tcp\n" +
            "\n" +
            "udrgmasezv\n" +
            "zotwyimlkq\n" +
            "\n" +
            "o\n" +
            "o\n" +
            "tdo\n" +
            "o\n" +
            "\n" +
            "ambertifpjuzvwk\n" +
            "dcyhwogqfiaxnlzps\n" +
            "\n" +
            "smzcqpikr\n" +
            "szmqcpkri\n" +
            "cqokmsrpzi\n" +
            "\n" +
            "tzkopc\n" +
            "pkcz\n" +
            "pckz\n" +
            "\n" +
            "avioqkyrntbesulwzp\n" +
            "oylhrtfzvainkuxbw\n" +
            "\n" +
            "hqieuv\n" +
            "hiqcu\n" +
            "ihwuq\n" +
            "\n" +
            "itfe\n" +
            "wcied\n" +
            "uvnigke\n" +
            "ltieq\n" +
            "\n" +
            "jrbmngvx\n" +
            "wousyqdiehcgk\n" +
            "ztfplg\n" +
            "\n" +
            "zdhewmyr\n" +
            "wjgqt\n" +
            "ynwdcef\n" +
            "kmvnwhfep\n" +
            "wyco\n" +
            "\n" +
            "x\n" +
            "x\n" +
            "x\n" +
            "x\n" +
            "\n" +
            "phkfsnxwce\n" +
            "dztiaygqu\n" +
            "jvrmltid\n" +
            "\n" +
            "ayhkqv\n" +
            "havyqk\n" +
            "vyhkaq\n" +
            "vyajenhgqk\n" +
            "vakhyq\n" +
            "\n" +
            "dxlepoksgznvuyjcihwqtf\n" +
            "lyqaihgexkcozwdsjnbtmfu\n" +
            "ysecldonhztfkruwxgjqi\n" +
            "\n" +
            "epo\n" +
            "azoeq\n" +
            "mfg\n" +
            "tbujywxr\n" +
            "eod\n" +
            "\n" +
            "myek\n" +
            "kmey\n" +
            "meky\n" +
            "\n" +
            "iwyngr\n" +
            "vishbag\n" +
            "kinsq\n" +
            "lzxoeticmudfp\n" +
            "nhjswiv\n" +
            "\n" +
            "fbtscavdzrkxeqyuhiw\n" +
            "orafstylxkgphmed\n" +
            "fehrsanktydx\n" +
            "\n" +
            "covl\n" +
            "ypkqdc\n" +
            "xzc\n" +
            "ejwsgafcbh\n" +
            "vcutm\n" +
            "\n" +
            "mlsfecori\n" +
            "ehpsya\n" +
            "\n" +
            "dpvgtqzocn\n" +
            "ngdvoqptzc\n" +
            "toqcdgvnpz\n" +
            "vdqptznocg\n" +
            "ncgzqdotvp\n" +
            "\n" +
            "adsqywe\n" +
            "msdeawq\n" +
            "edwaqs\n" +
            "vedwasnq\n" +
            "qdaswe\n" +
            "\n" +
            "bqmpnhvtoakiyr\n" +
            "roufkiapnqeym\n" +
            "\n" +
            "fydeiohqas\n" +
            "sqoycfhad\n" +
            "safyqhod\n" +
            "ghadsxfyqomv\n" +
            "\n" +
            "qdxmrofjwb\n" +
            "qwkidye\n" +
            "lgqyziawd\n" +
            "\n" +
            "erqsduihwmjcz\n" +
            "umericogzyjsqhn\n" +
            "\n" +
            "hsct\n" +
            "hsct\n" +
            "thcs\n" +
            "ctsh\n" +
            "\n" +
            "vtnbqai\n" +
            "qtianb\n" +
            "\n" +
            "tdwhrmbvyalqfojzicpxe\n" +
            "cltemhoxwbpqyrijvzad\n" +
            "wxjmpyzdqoeabichtrlv\n" +
            "ogzwhbdmtqxecvryjipla\n" +
            "\n" +
            "wnkjevsuqrtbfygih\n" +
            "jzagctiudpbqyfvhomkr\n" +
            "qtfkshvgryibujn\n" +
            "\n" +
            "qowgkyzsfetprnd\n" +
            "sgrdfepwnyzqtok\n" +
            "pgnrwdkzofyesqjt\n" +
            "wfcpkntezoyshgdlqr\n" +
            "dfrongetpszqwyk\n" +
            "\n" +
            "fdmxzviro\n" +
            "odcszimujfqaknx\n" +
            "xmoivfhdwz\n" +
            "yoidfzmvxbg\n" +
            "\n" +
            "nxmtopbehydczsrj\n" +
            "hrtspxjyiwczdngfb\n" +
            "uzjranxksdbltpyhv\n" +
            "\n" +
            "zoia\n" +
            "zioa\n" +
            "cazoi\n" +
            "\n" +
            "kwfnrcbjushlme\n" +
            "wsnmelhrjcubk\n" +
            "\n" +
            "lhf\n" +
            "hl\n" +
            "hl\n" +
            "\n" +
            "qvtia\n" +
            "vqal\n" +
            "ovqa\n" +
            "qva\n" +
            "valqy\n" +
            "\n" +
            "jxfkt\n" +
            "evhj\n" +
            "kgjo\n" +
            "puyasnjliz\n" +
            "xkmj\n" +
            "\n" +
            "cbhxvorjpgzd\n" +
            "dcbxgjhporzv\n" +
            "pjdbxhrogzvc\n" +
            "ogbrpjdvxzch\n" +
            "\n" +
            "ks\n" +
            "skh\n" +
            "sk";
}
