package advent2019;

import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

public class Day6Test {

    @Test
    public void problem1() {
        List<String> orbitsCompleted = new ArrayList<>();
        String[] orbitList = testInput.split("\n");
        List<Node> nodeList = new ArrayList<>();
        for (String n : orbitList) {
            String value = n.split("\\)")[0];
            if (getNode(nodeList, value) == null) {
                Node node = new Node();
                node.setValue(value);
                node.setOrbits(0);
                nodeList.add(node);
            }
        }
        for (String n : orbitList) {
            Node orbitee = getNode(nodeList, n.split("\\)")[0]);
            String orbiter = n.split("\\)")[1];
            Node child = new Node();
            child.setValue(orbiter);
            orbitee.getChildren().add(child);
        }
        int count = 0;
        for (Node node : nodeList) {
            count += node.getChildren().size();
            for (Node child : node.getChildren()) {
                getNode(nodeList, child.getValue()).getChildren().size();
                count += child.getChildren().size();
            }
        }
        System.out.println(count);
    }

    private Node getNode(List<Node> masterList, String c) {
        for (Node node : masterList) {
            if (node.getValue().equalsIgnoreCase(c)) {
                return node;
            }
        }
        return null;
    }

    private String testInput = "COM)B\n" +
            "B)C\n" +
            "C)D\n" +
            "D)E\n" +
            "E)F\n" +
            "B)G\n" +
            "G)H\n" +
            "D)I\n" +
            "E)J\n" +
            "J)K\n" +
            "K)L";

    private String input = "F6J)1YB\n" +
            "6LV)SG3\n" +
            "K7G)GD2\n" +
            "JC1)Y2W\n" +
            "43D)SP2\n" +
            "YQV)JKG\n" +
            "TD4)7SZ\n" +
            "H8T)43D\n" +
            "T1S)H8Y\n" +
            "1BW)H7F\n" +
            "PDV)93Q\n" +
            "2HK)Z93\n" +
            "37L)1FF\n" +
            "35Y)MZH\n" +
            "7NY)DWF\n" +
            "YLS)5B6\n" +
            "N66)QLD\n" +
            "T9K)TMS\n" +
            "JZF)7TC\n" +
            "9QD)YRG\n" +
            "5T2)CYY\n" +
            "DBP)FG7\n" +
            "JVN)N7N\n" +
            "Q78)K9T\n" +
            "6CZ)D66\n" +
            "WD3)LNP\n" +
            "7YB)Y9T\n" +
            "Z3S)115\n" +
            "2PD)RC7\n" +
            "XZS)DZD\n" +
            "PCP)3YG\n" +
            "QYH)3CV\n" +
            "F3M)1SZ\n" +
            "37W)C4L\n" +
            "W1Y)T5F\n" +
            "S9V)TD7\n" +
            "L52)81R\n" +
            "7F1)45V\n" +
            "858)YN9\n" +
            "4JB)RMY\n" +
            "NL4)F8R\n" +
            "V6D)KPP\n" +
            "ZMR)KXH\n" +
            "X7Y)N3G\n" +
            "TRT)W5B\n" +
            "FHH)MNV\n" +
            "725)W9Y\n" +
            "QYG)D7S\n" +
            "LQX)ZQK\n" +
            "KTL)G6X\n" +
            "Z93)GZS\n" +
            "W28)BFC\n" +
            "PR1)9B6\n" +
            "MNX)Y76\n" +
            "YZG)1WK\n" +
            "X6S)H9M\n" +
            "GPY)HLS\n" +
            "7XR)G7Q\n" +
            "5B1)MVF\n" +
            "3GK)XTS\n" +
            "KFK)36G\n" +
            "5B6)PD9\n" +
            "TL4)NXV\n" +
            "265)84G\n" +
            "Z5T)B78\n" +
            "JBB)LG9\n" +
            "GLM)1H1\n" +
            "H6F)P9N\n" +
            "DZP)MFM\n" +
            "ZNL)FHH\n" +
            "QRZ)M8Q\n" +
            "QQ6)1KW\n" +
            "SG3)GPW\n" +
            "D85)QX4\n" +
            "W85)Y98\n" +
            "4SF)R39\n" +
            "7RL)54X\n" +
            "GX8)6QS\n" +
            "MD4)6ZK\n" +
            "5ST)NHM\n" +
            "6GS)9G6\n" +
            "6M7)8FF\n" +
            "GZS)XFJ\n" +
            "NHM)SMF\n" +
            "Y8X)KTL\n" +
            "V8R)9N5\n" +
            "PVX)G41\n" +
            "JP5)TRV\n" +
            "29T)LVJ\n" +
            "B78)9FH\n" +
            "HGW)MXC\n" +
            "D3K)PX5\n" +
            "BMQ)7KP\n" +
            "5FP)CSK\n" +
            "X7T)2JP\n" +
            "TD7)5BW\n" +
            "9BG)2LR\n" +
            "DQS)FKY\n" +
            "XZC)W1J\n" +
            "3LR)DVC\n" +
            "FMK)3WS\n" +
            "Y7C)177\n" +
            "C7X)LSN\n" +
            "HG3)SZM\n" +
            "P9N)KNV\n" +
            "YW9)WL7\n" +
            "MD7)XZC\n" +
            "RC1)S1N\n" +
            "M8Q)LDZ\n" +
            "23V)ZPH\n" +
            "NR2)WYF\n" +
            "VN8)2XR\n" +
            "44R)KH9\n" +
            "BHZ)ZMG\n" +
            "G89)38T\n" +
            "8CC)6VK\n" +
            "7YS)3LL\n" +
            "KZG)V5V\n" +
            "G1B)GNM\n" +
            "KPP)64T\n" +
            "B8P)W9T\n" +
            "2VT)FL6\n" +
            "WWC)Y6F\n" +
            "KHT)GHX\n" +
            "83D)NZK\n" +
            "64T)JD7\n" +
            "VVL)7RB\n" +
            "3WK)1NW\n" +
            "H36)Z4K\n" +
            "8L8)M2Y\n" +
            "7R5)RSS\n" +
            "N8V)V8G\n" +
            "NG4)YKB\n" +
            "SHH)PVX\n" +
            "PN2)2L5\n" +
            "ZRT)J2C\n" +
            "LDZ)73H\n" +
            "CSK)H47\n" +
            "QDB)9W9\n" +
            "2D4)26N\n" +
            "YJT)7YS\n" +
            "DX8)X7Y\n" +
            "MW3)6YY\n" +
            "TLC)KJM\n" +
            "B58)5XY\n" +
            "Q6R)WXJ\n" +
            "P8F)QNY\n" +
            "Y6F)JWT\n" +
            "CRD)FVT\n" +
            "KLW)TMQ\n" +
            "9M1)TWB\n" +
            "NHZ)3CS\n" +
            "9ZL)CRD\n" +
            "R9H)HM1\n" +
            "YD5)TX1\n" +
            "FPR)4P4\n" +
            "GR6)T1S\n" +
            "7NZ)X1G\n" +
            "WJZ)4LY\n" +
            "QCG)D3G\n" +
            "685)PTQ\n" +
            "FZJ)4NP\n" +
            "56S)78G\n" +
            "CC7)ZWF\n" +
            "XBT)7ZQ\n" +
            "BH3)MRP\n" +
            "2W1)P61\n" +
            "QS6)M4N\n" +
            "X2P)Y28\n" +
            "5TG)VW5\n" +
            "DM7)893\n" +
            "X2P)JY1\n" +
            "XKV)WLK\n" +
            "XFJ)QP3\n" +
            "PNH)7GL\n" +
            "DNH)FPN\n" +
            "ZTK)9H9\n" +
            "FFN)M3W\n" +
            "FZR)741\n" +
            "54S)C1Z\n" +
            "S2M)ZNL\n" +
            "7DW)TWY\n" +
            "FKY)RLH\n" +
            "SKG)KLW\n" +
            "ML8)6PR\n" +
            "PS2)FS6\n" +
            "WSV)R4R\n" +
            "MYQ)3JX\n" +
            "ZYP)LRB\n" +
            "96X)Q7Z\n" +
            "7M9)RC1\n" +
            "QKQ)QYH\n" +
            "TPB)YHM\n" +
            "TX1)4PK\n" +
            "X9Q)3RC\n" +
            "ZZ3)ZJT\n" +
            "HF3)HPL\n" +
            "ZPH)G7G\n" +
            "T6N)QG1\n" +
            "ZJT)FVH\n" +
            "J2L)DT4\n" +
            "6LP)HKV\n" +
            "TJJ)83L\n" +
            "CNH)6M7\n" +
            "B55)V2V\n" +
            "1TK)FGT\n" +
            "NLQ)968\n" +
            "37H)F7V\n" +
            "SZM)XKV\n" +
            "5ZF)JL1\n" +
            "2C6)YVD\n" +
            "Y55)H3N\n" +
            "TJZ)R1D\n" +
            "F79)NJT\n" +
            "XC3)QTM\n" +
            "1RX)WMY\n" +
            "L5N)ZTK\n" +
            "N43)TSG\n" +
            "PFC)61H\n" +
            "WD7)WH2\n" +
            "11D)68G\n" +
            "NXV)84Z\n" +
            "NMG)MNX\n" +
            "LRZ)N31\n" +
            "8PQ)MJC\n" +
            "W15)WZ3\n" +
            "V5H)21N\n" +
            "DXX)Z79\n" +
            "L8M)57F\n" +
            "GYD)WQ6\n" +
            "4FH)P7L\n" +
            "W3L)1M2\n" +
            "F7V)Y3L\n" +
            "64K)6LP\n" +
            "GBK)J1M\n" +
            "GNM)BMQ\n" +
            "FMP)H36\n" +
            "865)ZMW\n" +
            "5ZH)931\n" +
            "4P4)2DN\n" +
            "7PT)DM7\n" +
            "F4X)1VY\n" +
            "BSM)JWV\n" +
            "V1J)W15\n" +
            "HGW)SS8\n" +
            "JK5)MD5\n" +
            "Z79)WQZ\n" +
            "1V6)PN2\n" +
            "3Z1)VQR\n" +
            "G2B)333\n" +
            "C5D)F3M\n" +
            "W5B)RBC\n" +
            "3R9)C7X\n" +
            "115)5JK\n" +
            "KMG)9G9\n" +
            "DYR)1QX\n" +
            "GLR)KNJ\n" +
            "C59)W28\n" +
            "V5M)FMP\n" +
            "DGY)LQN\n" +
            "WVY)JLW\n" +
            "376)YJT\n" +
            "LBK)ZCV\n" +
            "JWD)YPX\n" +
            "98D)CWQ\n" +
            "P3H)9ZL\n" +
            "VJG)596\n" +
            "R62)QDK\n" +
            "KC6)5B1\n" +
            "WDF)MN4\n" +
            "4D8)K74\n" +
            "BXF)6RY\n" +
            "FNX)SKG\n" +
            "FPN)2DB\n" +
            "3KH)H87\n" +
            "YFW)FVN\n" +
            "8JS)6J8\n" +
            "C4G)MMV\n" +
            "TD3)FGL\n" +
            "1TX)Z9M\n" +
            "18G)Y55\n" +
            "RCS)ZMR\n" +
            "4F2)CNX\n" +
            "YKP)54S\n" +
            "RWG)4DH\n" +
            "RR7)JQL\n" +
            "N6H)3YV\n" +
            "BLL)PCP\n" +
            "DJP)MJR\n" +
            "7ZK)4HV\n" +
            "9H6)BMX\n" +
            "DT4)GK5\n" +
            "WYF)P59\n" +
            "QPX)NKZ\n" +
            "177)BMY\n" +
            "LHK)4ZZ\n" +
            "HN7)JWD\n" +
            "1TL)RX6\n" +
            "WD5)SNT\n" +
            "R4R)CVL\n" +
            "4JN)DC9\n" +
            "JXW)1RX\n" +
            "VBR)99Q\n" +
            "T53)KLR\n" +
            "5T1)7HH\n" +
            "6MH)3H4\n" +
            "HHN)PHL\n" +
            "BNM)RJ4\n" +
            "7XM)QYG\n" +
            "V9L)TJN\n" +
            "Y79)BSP\n" +
            "LLF)5KJ\n" +
            "VS5)5S9\n" +
            "DJY)KTQ\n" +
            "Q57)37H\n" +
            "HPL)9M1\n" +
            "YWN)YTR\n" +
            "FW4)8Y4\n" +
            "T4F)NHZ\n" +
            "WQ6)61N\n" +
            "8LF)BVP\n" +
            "5MQ)Z5F\n" +
            "KG5)N99\n" +
            "NZK)YNY\n" +
            "8FM)9ZM\n" +
            "27V)C2V\n" +
            "VXT)KMG\n" +
            "5W6)B2N\n" +
            "X2R)VJT\n" +
            "JQL)J91\n" +
            "YWP)89X\n" +
            "T42)V5M\n" +
            "2Z2)H63\n" +
            "GXJ)YWN\n" +
            "JJG)L7H\n" +
            "S3V)TL4\n" +
            "RFC)4LJ\n" +
            "YD5)QJ5\n" +
            "TNW)BWL\n" +
            "1B9)7NZ\n" +
            "P8G)6D1\n" +
            "YVD)BGV\n" +
            "GXX)RR7\n" +
            "C8W)CFB\n" +
            "YHM)J4D\n" +
            "FZX)SFP\n" +
            "D5S)FS2\n" +
            "FZC)YGK\n" +
            "PJL)Z8G\n" +
            "SF6)YG5\n" +
            "R42)414\n" +
            "57F)SF6\n" +
            "LRD)F9T\n" +
            "6YV)75H\n" +
            "1NW)ZK6\n" +
            "XN5)9HM\n" +
            "MN4)TRT\n" +
            "DKG)NF8\n" +
            "6PN)PS2\n" +
            "Y76)CNS\n" +
            "XWF)85R\n" +
            "D63)J9M\n" +
            "235)CYJ\n" +
            "414)R62\n" +
            "NQM)9JM\n" +
            "D9V)JP5\n" +
            "LVJ)WTF\n" +
            "D94)RYS\n" +
            "6H7)DHN\n" +
            "RBW)B1W\n" +
            "7SS)S2M\n" +
            "GT8)278\n" +
            "PWL)L9V\n" +
            "MXC)3K6\n" +
            "7HB)Q9M\n" +
            "9L5)DYR\n" +
            "TMS)4MC\n" +
            "9XQ)TD3\n" +
            "65K)Q6R\n" +
            "LTG)ZF1\n" +
            "WKK)RX3\n" +
            "ST3)6K3\n" +
            "YS6)7ZK\n" +
            "G9C)8YP\n" +
            "GHB)8Y6\n" +
            "PP4)QDD\n" +
            "QLD)7CF\n" +
            "QMG)KNS\n" +
            "WZ3)F31\n" +
            "PS3)KFB\n" +
            "FQC)YS2\n" +
            "HM1)T68\n" +
            "VYS)PDD\n" +
            "J8S)GR9\n" +
            "BWS)7M9\n" +
            "7RM)9QD\n" +
            "DWM)MFX\n" +
            "RQK)X2P\n" +
            "RGF)9FR\n" +
            "9KL)L48\n" +
            "7FG)PS3\n" +
            "2V1)7BJ\n" +
            "TFW)X4T\n" +
            "WHD)7ZF\n" +
            "YNY)72H\n" +
            "78D)9MZ\n" +
            "LG9)YBL\n" +
            "5BT)725\n" +
            "6B1)81D\n" +
            "MPD)MZN\n" +
            "KJM)YLS\n" +
            "XTS)GBK\n" +
            "MD5)RDS\n" +
            "2QV)8P3\n" +
            "45V)LTG\n" +
            "8KR)GYW\n" +
            "H9J)7V5\n" +
            "MJL)FFN\n" +
            "5SB)JD3\n" +
            "L7N)GDY\n" +
            "J1M)HSF\n" +
            "FVN)LTQ\n" +
            "NCN)T2H\n" +
            "R3X)C1Q\n" +
            "YFJ)S54\n" +
            "WXJ)HN7\n" +
            "38T)JNF\n" +
            "9RM)RBN\n" +
            "WCP)9M8\n" +
            "PZ9)BB4\n" +
            "RBM)9X7\n" +
            "CGM)8PQ\n" +
            "GQG)5G9\n" +
            "968)D3N\n" +
            "YKB)C59\n" +
            "JWT)MLP\n" +
            "RDD)XNY\n" +
            "KLR)S9V\n" +
            "COM)LGH\n" +
            "LY2)JC8\n" +
            "S6Z)LRG\n" +
            "WTX)7DF\n" +
            "HN7)BY5\n" +
            "8CC)NL4\n" +
            "655)TWM\n" +
            "6JV)NH2\n" +
            "GRG)SV3\n" +
            "5G8)NRZ\n" +
            "XG9)172\n" +
            "6GG)B7D\n" +
            "QCK)2RJ\n" +
            "NY3)QKQ\n" +
            "TRV)KVC\n" +
            "B92)83D\n" +
            "V21)Z1S\n" +
            "3LP)18M\n" +
            "3BX)LTN\n" +
            "3YV)VZZ\n" +
            "829)SS6\n" +
            "4SM)H6F\n" +
            "CCF)DZP\n" +
            "MBJ)SLW\n" +
            "XS2)V5H\n" +
            "HVR)4BC\n" +
            "R23)XZV\n" +
            "931)XGD\n" +
            "5DZ)W1N\n" +
            "3RB)VKY\n" +
            "JD3)F1W\n" +
            "B99)4F4\n" +
            "464)12L\n" +
            "9DV)2Z2\n" +
            "YTR)6J7\n" +
            "2VY)N86\n" +
            "4F4)NXW\n" +
            "6V5)YFW\n" +
            "KQP)BKJ\n" +
            "9H9)G91\n" +
            "KC6)4W2\n" +
            "7Q8)YOU\n" +
            "1M2)88F\n" +
            "9G4)JPD\n" +
            "9QD)YVF\n" +
            "T1S)DYD\n" +
            "NJ7)4SF\n" +
            "M94)3PJ\n" +
            "8GS)5JW\n" +
            "5G9)W7W\n" +
            "GPW)LN8\n" +
            "SDN)K7G\n" +
            "16X)CHH\n" +
            "1GQ)4KJ\n" +
            "SM5)6M4\n" +
            "D3N)31J\n" +
            "R9B)QBF\n" +
            "MVF)L7T\n" +
            "JPR)K1B\n" +
            "J6L)CC7\n" +
            "92N)BSM\n" +
            "TT5)RHW\n" +
            "NMF)18G\n" +
            "LTQ)LLF\n" +
            "9WS)9XQ\n" +
            "BMX)B5V\n" +
            "73P)8NF\n" +
            "SS8)JQT\n" +
            "NRF)JBB\n" +
            "L6D)SDN\n" +
            "6NX)QYW\n" +
            "VWR)G9C\n" +
            "4WL)KV4\n" +
            "YN9)D9V\n" +
            "X1G)6YW\n" +
            "XJV)NGK\n" +
            "ZSN)9H6\n" +
            "14S)9J3\n" +
            "Z9M)CZW\n" +
            "CYJ)FBT\n" +
            "347)WBN\n" +
            "JS9)6LX\n" +
            "DD2)293\n" +
            "738)7JR\n" +
            "V5V)5ZF\n" +
            "9FR)C5D\n" +
            "12L)VS5\n" +
            "84T)CR1\n" +
            "RN6)M5N\n" +
            "4W2)YWG\n" +
            "PXL)1B1\n" +
            "Q6R)7JF\n" +
            "PFK)Y79\n" +
            "TT2)7NM\n" +
            "WZ3)WD3\n" +
            "26C)X4J\n" +
            "PJL)69B\n" +
            "HJS)G95\n" +
            "W9T)H1W\n" +
            "TSN)6PN\n" +
            "PF1)NLV\n" +
            "7YL)VCS\n" +
            "52Q)G6P\n" +
            "3BZ)QS6\n" +
            "7KD)T6N\n" +
            "21X)MGN\n" +
            "5JV)DL7\n" +
            "ZPR)2C6\n" +
            "NYH)NPD\n" +
            "CGG)NG4\n" +
            "K8K)CKJ\n" +
            "1ZC)Y7C\n" +
            "NH2)HGW\n" +
            "YBW)5MR\n" +
            "7NM)T1J\n" +
            "X6H)DNH\n" +
            "TZ2)C13\n" +
            "F5G)VBR\n" +
            "WDX)K2S\n" +
            "486)858\n" +
            "76P)TNG\n" +
            "C4G)D5S\n" +
            "D4D)TSN\n" +
            "QX4)493\n" +
            "VQR)KKK\n" +
            "BJS)CM6\n" +
            "QX7)RCS\n" +
            "M15)7PT\n" +
            "KHD)F3B\n" +
            "4F2)49P\n" +
            "RP2)KSN\n" +
            "F9L)FZC\n" +
            "WXV)LRZ\n" +
            "M2Y)BHZ\n" +
            "XNY)DWM\n" +
            "D82)GMP\n" +
            "BHQ)GT8\n" +
            "5T1)XP9\n" +
            "3JX)BPM\n" +
            "38R)CS7\n" +
            "X4J)DTZ\n" +
            "X94)9WS\n" +
            "MGN)WKQ\n" +
            "9GV)TLC\n" +
            "8BX)TKM\n" +
            "ZRT)HXH\n" +
            "J4D)JK5\n" +
            "2B9)3RB\n" +
            "6B8)GHJ\n" +
            "16W)7XR\n" +
            "PD7)32Q\n" +
            "CNS)KQP\n" +
            "WZ7)5SB\n" +
            "CFB)K8H\n" +
            "LWS)2M1\n" +
            "2WF)G4B\n" +
            "BSP)J48\n" +
            "QYF)F9L\n" +
            "GD2)1TK\n" +
            "BFC)8FM\n" +
            "21N)4D8\n" +
            "4W5)7Z9\n" +
            "T68)C3N\n" +
            "GNY)X93\n" +
            "KSX)ZYP\n" +
            "ZYZ)LTW\n" +
            "37L)PP4\n" +
            "KDG)2B9\n" +
            "LRB)4WL\n" +
            "HNZ)BX5\n" +
            "2LR)MJL\n" +
            "GGB)THL\n" +
            "DLV)C3M\n" +
            "1V8)WDX\n" +
            "9MZ)FR7\n" +
            "NZ7)L5N\n" +
            "NRZ)GLM\n" +
            "TKM)7YB\n" +
            "8SW)7Q8\n" +
            "KV4)4FH\n" +
            "MC8)SVW\n" +
            "8SW)5KB\n" +
            "RMY)X6L\n" +
            "3PB)XBQ\n" +
            "RMW)5BT\n" +
            "BB4)VVL\n" +
            "F3S)TPB\n" +
            "BFG)KYX\n" +
            "3CV)F4K\n" +
            "B15)7PY\n" +
            "G4Y)JVN\n" +
            "P7L)Y3K\n" +
            "QTM)98D\n" +
            "D28)5TG\n" +
            "C1Z)J2L\n" +
            "VY2)V36\n" +
            "V1J)GW9\n" +
            "CKJ)WTX\n" +
            "LSN)TW9\n" +
            "CNX)ZHM\n" +
            "5Q7)1MV\n" +
            "MZN)4BX\n" +
            "H78)LSH\n" +
            "G7G)YXK\n" +
            "3HB)ZZN\n" +
            "ZRB)FW4\n" +
            "D69)6JD\n" +
            "PCN)MQH\n" +
            "N8C)TZ2\n" +
            "KNJ)HWR\n" +
            "MYQ)265\n" +
            "37S)GPY\n" +
            "7RB)B7Q\n" +
            "6YW)BKS\n" +
            "W2L)LXD\n" +
            "73H)K2H\n" +
            "G7G)1Q8\n" +
            "J2C)6GM\n" +
            "7ZF)ZRT\n" +
            "CWJ)7NY\n" +
            "3F6)CNH\n" +
            "VQB)D63\n" +
            "596)31R\n" +
            "SLW)FLV\n" +
            "Y3L)MYQ\n" +
            "XB2)FF3\n" +
            "8HQ)S2H\n" +
            "Z1S)NKR\n" +
            "8MX)HTX\n" +
            "N84)F6J\n" +
            "4WK)R1B\n" +
            "DPG)78D\n" +
            "K2S)8GS\n" +
            "VVB)63J\n" +
            "8CT)9F1\n" +
            "RNS)RY9\n" +
            "FGT)DN2\n" +
            "TWB)PYS\n" +
            "NVD)Z6T\n" +
            "7XM)R3X\n" +
            "R14)SBV\n" +
            "8Y4)Z5T\n" +
            "J48)PFC\n" +
            "Z5F)GRG\n" +
            "Z9R)X6H\n" +
            "SQX)8Q3\n" +
            "D5F)M7V\n" +
            "BX5)1G1\n" +
            "D82)RP2\n" +
            "N31)KWX\n" +
            "14J)BXB\n" +
            "SH6)41V\n" +
            "J6L)X9Q\n" +
            "XVS)S88\n" +
            "4KH)D85\n" +
            "72S)WMH\n" +
            "1K1)G4Y\n" +
            "MBZ)T4F\n" +
            "DYD)P8V\n" +
            "BBZ)GW2\n" +
            "FQC)S5H\n" +
            "TX1)WHD\n" +
            "R4T)N8L\n" +
            "KH9)6GZ\n" +
            "R1B)77D\n" +
            "JC8)3N6\n" +
            "C13)VV9\n" +
            "4PK)S33\n" +
            "KG5)6LV\n" +
            "9ZM)F5N\n" +
            "WMS)X6D\n" +
            "H8Y)BLL\n" +
            "NQH)W66\n" +
            "N8L)FZJ\n" +
            "YG5)5RN\n" +
            "TWM)LHK\n" +
            "DPD)DLV\n" +
            "Q9M)6LG\n" +
            "4PQ)PZD\n" +
            "DHN)SB4\n" +
            "X43)9L5\n" +
            "X9C)8W5\n" +
            "8KJ)GQG\n" +
            "CVY)F5Y\n" +
            "T5F)QPX\n" +
            "5F5)SQX\n" +
            "2XR)YBW\n" +
            "RY9)5R2\n" +
            "54K)CWR\n" +
            "KRD)BTB\n" +
            "YTY)NVP\n" +
            "6J7)KX5\n" +
            "3LL)L7N\n" +
            "1FP)LBK\n" +
            "V3R)K3Q\n" +
            "G2B)B62\n" +
            "K8H)MBJ\n" +
            "7TC)BJX\n" +
            "C8V)R14\n" +
            "1KW)L21\n" +
            "ZB2)JPR\n" +
            "P3W)C8V\n" +
            "GQ4)TT2\n" +
            "TWV)HBK\n" +
            "2XR)QJP\n" +
            "L8J)FNX\n" +
            "K14)KWL\n" +
            "F4J)KHT\n" +
            "49P)56S\n" +
            "GMT)K4S\n" +
            "FZ1)NSY\n" +
            "QYW)RMW\n" +
            "FVK)F3S\n" +
            "Q7Z)RGF\n" +
            "Q44)23V\n" +
            "C3K)TPY\n" +
            "5RN)D7B\n" +
            "QBN)11W\n" +
            "1S1)QVG\n" +
            "MFM)D7G\n" +
            "W4H)4CN\n" +
            "JVJ)4GB\n" +
            "1KQ)P1B\n" +
            "W4H)35Y\n" +
            "J4B)RFC\n" +
            "T95)RDF\n" +
            "Q9G)NYH\n" +
            "Y28)RTL\n" +
            "WWL)363\n" +
            "6DT)9YR\n" +
            "G95)G4J\n" +
            "R4S)YFL\n" +
            "C1Q)MC8\n" +
            "7DJ)72S\n" +
            "55B)5ZD\n" +
            "9R7)8VZ\n" +
            "9VH)JS9\n" +
            "41M)N43\n" +
            "KSN)6B8\n" +
            "RYS)1BW\n" +
            "5LY)88G\n" +
            "ZHD)CY2\n" +
            "4MC)P3H\n" +
            "YFL)PW3\n" +
            "69B)5DZ\n" +
            "S1X)LBB\n" +
            "B7D)PDF\n" +
            "9HM)S3V\n" +
            "WH2)M94\n" +
            "PX5)29T\n" +
            "K2N)TZT\n" +
            "VK9)VN8\n" +
            "JNF)3KH\n" +
            "DN2)H8F\n" +
            "8W4)FQ9\n" +
            "ZVB)B8W\n" +
            "FZX)5T1\n" +
            "X3Q)T42\n" +
            "3YT)21X\n" +
            "NGK)KFG\n" +
            "G91)8R2\n" +
            "8LS)C9P\n" +
            "6LG)N8C\n" +
            "JJZ)BJS\n" +
            "TNG)829\n" +
            "493)P7G\n" +
            "WLK)CWJ\n" +
            "4BX)G2B\n" +
            "81R)SNG\n" +
            "ZK6)SCN\n" +
            "L9D)7F1\n" +
            "S88)3Z1\n" +
            "53D)ZJV\n" +
            "6RY)PBD\n" +
            "8W5)2VL\n" +
            "JL1)MBZ\n" +
            "RJ4)RFX\n" +
            "LRG)QSB\n" +
            "QP3)HG3\n" +
            "HXH)DX8\n" +
            "4MC)R2C\n" +
            "NRZ)1LK\n" +
            "H9V)347\n" +
            "9N5)YRH\n" +
            "RWG)MKC\n" +
            "9G6)Z9R\n" +
            "3CS)FMK\n" +
            "5LF)JS8\n" +
            "5S9)MXQ\n" +
            "D7S)3WK\n" +
            "K3Q)HVR\n" +
            "DVC)DWN\n" +
            "3WS)WWC\n" +
            "F9T)2V1\n" +
            "GRP)4JN\n" +
            "3R9)2PD\n" +
            "4GB)WTB\n" +
            "H47)76P\n" +
            "WHM)R21\n" +
            "FR7)14H\n" +
            "5WP)64K\n" +
            "HLS)K14\n" +
            "LD6)KSX\n" +
            "NQM)9NM\n" +
            "NKR)DG3\n" +
            "WTB)ZRB\n" +
            "BVS)TCC\n" +
            "5JK)1ZC\n" +
            "GNV)ZHD\n" +
            "M7V)8CC\n" +
            "ZZN)9BG\n" +
            "C3S)2YC\n" +
            "RQW)TFW\n" +
            "QG1)QM6\n" +
            "D85)D3K\n" +
            "BCP)1TX\n" +
            "1XP)HF3\n" +
            "5LY)RN6\n" +
            "FZJ)37S\n" +
            "KF3)73P\n" +
            "MMV)55B\n" +
            "835)DBP\n" +
            "KFG)WKW\n" +
            "7BL)7VX\n" +
            "G6P)VP8\n" +
            "5H3)L8M\n" +
            "J91)3B5\n" +
            "1QX)3BX\n" +
            "QNC)PK6\n" +
            "MBC)BD3\n" +
            "Y9T)3F6\n" +
            "3N6)YS6\n" +
            "7SZ)3LP\n" +
            "XXH)655\n" +
            "C44)J3G\n" +
            "ZWF)41D\n" +
            "H7F)TK6\n" +
            "ZLD)5Q7\n" +
            "JWV)835\n" +
            "78K)ML8\n" +
            "LWR)1TL\n" +
            "GMJ)53D\n" +
            "ZNL)486\n" +
            "SBH)DY6\n" +
            "3LR)8LF\n" +
            "7Y3)7KK\n" +
            "6M4)JMM\n" +
            "PD9)GV9\n" +
            "CY2)XQP\n" +
            "ZYP)ZP9\n" +
            "5GV)CKM\n" +
            "M6M)FK8\n" +
            "SCN)GRN\n" +
            "PFK)JT8\n" +
            "C13)B92\n" +
            "QDX)JJZ\n" +
            "HJ8)QRZ\n" +
            "W7J)J4G\n" +
            "6YY)TRH\n" +
            "XCD)L8J\n" +
            "5MP)5N5\n" +
            "TMQ)9DV\n" +
            "SNV)65K\n" +
            "SWZ)TYL\n" +
            "HWR)K2N\n" +
            "PZD)CJ3\n" +
            "CYY)PXW\n" +
            "414)TWR\n" +
            "63J)X9C\n" +
            "W85)S8Z\n" +
            "VV9)LRD\n" +
            "VQY)MW3\n" +
            "H6M)QCK\n" +
            "PTQ)R29\n" +
            "688)YFJ\n" +
            "CC8)KF3\n" +
            "YRG)KZG\n" +
            "PBQ)XB2\n" +
            "9M8)WYD\n" +
            "Y3K)4JW\n" +
            "9FH)H9J\n" +
            "QPX)VK9\n" +
            "68G)9HZ\n" +
            "FVC)JWR\n" +
            "H1M)8KJ\n" +
            "BTB)FPR\n" +
            "6LX)ZLT\n" +
            "83L)7LJ\n" +
            "ZP9)CLH\n" +
            "246)MZ9\n" +
            "ZQK)246\n" +
            "LTW)LVK\n" +
            "88F)JNT\n" +
            "BXB)2VM\n" +
            "2TW)PZM\n" +
            "BQX)CGG\n" +
            "WKW)WDF\n" +
            "PPH)GYD\n" +
            "RTL)B99\n" +
            "J9M)M6P\n" +
            "LGH)BNM\n" +
            "MBQ)16W\n" +
            "G7Q)1XP\n" +
            "LBB)XVS\n" +
            "FS2)P68\n" +
            "L9V)85V\n" +
            "3PJ)RWJ\n" +
            "HX4)8HQ\n" +
            "FGD)3CR\n" +
            "D66)GXX\n" +
            "41V)T3N\n" +
            "RY5)2C9\n" +
            "DX6)J5T\n" +
            "TWR)8KR\n" +
            "KNV)VTM\n" +
            "2D4)92N\n" +
            "MZH)4H8\n" +
            "KTQ)VY2\n" +
            "6JD)BBZ\n" +
            "741)7BD\n" +
            "C2V)VQB\n" +
            "7Z9)NQH\n" +
            "LL9)B14\n" +
            "32Q)BBM\n" +
            "W2L)YZG\n" +
            "6ZK)RNQ\n" +
            "WWM)376\n" +
            "XQP)DXX\n" +
            "1LK)DW8\n" +
            "FQ9)6XK\n" +
            "YPX)5ZH\n" +
            "ZWX)8SW\n" +
            "1SJ)9L7\n" +
            "QY1)CGM\n" +
            "9NM)V8R\n" +
            "1K5)2VT\n" +
            "GRN)256\n" +
            "CFK)HJ8\n" +
            "V36)3BM\n" +
            "18M)LWS\n" +
            "1FP)PFK\n" +
            "2Y4)BD2\n" +
            "WQ6)QSK\n" +
            "VTM)FCP\n" +
            "GW9)ZWX\n" +
            "QNY)SJG\n" +
            "T3N)5W6\n" +
            "L56)QFS\n" +
            "L7T)WKK\n" +
            "JPD)7RM\n" +
            "4GB)153\n" +
            "7VX)RQQ\n" +
            "FKT)ZZ3\n" +
            "YGK)HZY\n" +
            "Z65)PBQ\n" +
            "MJC)CGN\n" +
            "PCN)5GV\n" +
            "V2V)2D4\n" +
            "R29)V97\n" +
            "C4L)DC5\n" +
            "26N)8JS\n" +
            "1VY)4KH\n" +
            "56S)FGD\n" +
            "QDK)G71\n" +
            "5KB)W2L\n" +
            "XN5)J2D\n" +
            "THL)HHN\n" +
            "YJ6)NCN\n" +
            "BT7)YVH\n" +
            "DWF)V1J\n" +
            "P1B)FQC\n" +
            "256)1XN\n" +
            "CS7)D53\n" +
            "NF8)B23\n" +
            "JPV)8J4\n" +
            "8Z8)GLR\n" +
            "LG9)9G4\n" +
            "N99)44R\n" +
            "3BM)8BX\n" +
            "QL6)16H\n" +
            "CR1)KRC\n" +
            "VW5)1K1\n" +
            "L7H)2W1\n" +
            "GYH)ZSN\n" +
            "XNT)ZM7\n" +
            "THL)L5C\n" +
            "KPP)5FP\n" +
            "CM6)J9S\n" +
            "RBM)VXT\n" +
            "5H6)JFH\n" +
            "8YP)ZB2\n" +
            "2M1)FVK\n" +
            "K9N)YYN\n" +
            "G4J)LY2\n" +
            "7LJ)DRS\n" +
            "JFH)7FG\n" +
            "R42)89T\n" +
            "KQR)182\n" +
            "BGV)CCF\n" +
            "7HS)3P9\n" +
            "CWR)BBG\n" +
            "C3N)GNY\n" +
            "2V3)3R9\n" +
            "331)PWL\n" +
            "GYW)5N2\n" +
            "CW1)T56\n" +
            "7MF)F4J\n" +
            "97J)14J\n" +
            "LSH)426\n" +
            "W1N)8Z8\n" +
            "K14)ZNJ\n" +
            "ZJV)DJY\n" +
            "7KK)V6D\n" +
            "M5N)2Y4\n" +
            "TYL)8TY\n" +
            "Y4K)78K\n" +
            "S2H)PP3\n" +
            "LNH)YYR\n" +
            "PDF)97J\n" +
            "NSY)2V3\n" +
            "WKT)F7Q\n" +
            "V4Z)PD7\n" +
            "ZPM)K5Z\n" +
            "QJ5)7MF\n" +
            "C3M)ZPR\n" +
            "4DH)MBC\n" +
            "426)JXW\n" +
            "F5N)PJL\n" +
            "6GZ)6GS\n" +
            "ZRH)G1B\n" +
            "KTQ)3PB\n" +
            "KMG)F56\n" +
            "JQT)C3K\n" +
            "HKV)SWQ\n" +
            "4JW)XR4\n" +
            "5NY)P8G\n" +
            "7H5)7DW\n" +
            "1Q8)464\n" +
            "CDP)SBH\n" +
            "FMH)8MX\n" +
            "H1W)WJZ\n" +
            "DC5)HJS\n" +
            "J2D)3LR\n" +
            "K4S)L56\n" +
            "SVW)XR9\n" +
            "RFX)G59\n" +
            "KRC)ZLD\n" +
            "JRP)6MH\n" +
            "5FP)KQD\n" +
            "JF8)M6M\n" +
            "DGY)5H3\n" +
            "5R2)1B9\n" +
            "3N6)VJG\n" +
            "2TY)N3Q\n" +
            "TD3)J3X\n" +
            "J4G)5MP\n" +
            "52D)6NX\n" +
            "R4P)L52\n" +
            "Z8G)4F2\n" +
            "L5C)37W\n" +
            "NVP)FZ1\n" +
            "1RX)3ZH\n" +
            "LPL)6DT\n" +
            "278)9Z7\n" +
            "M3W)W4H\n" +
            "84Z)Z51\n" +
            "RSS)KC6\n" +
            "7JF)11D\n" +
            "ZV3)QYF\n" +
            "TCC)L9D\n" +
            "1V6)C4G\n" +
            "XZV)LQX\n" +
            "8TY)N8B\n" +
            "13W)R23\n" +
            "Y6S)8KQ\n" +
            "LXD)1S1\n" +
            "85V)PNB\n" +
            "SNT)JPV\n" +
            "153)FZX\n" +
            "1G1)NR2\n" +
            "KVC)VY8\n" +
            "641)8RG\n" +
            "1HG)CDY\n" +
            "BK1)Q9G\n" +
            "W67)WZ5\n" +
            "ZPH)GYH\n" +
            "W9Y)GRP\n" +
            "BKS)V4Z\n" +
            "NZ7)SNV\n" +
            "NTK)XCY\n" +
            "9D1)26C\n" +
            "HZY)5F5\n" +
            "WYD)GT3\n" +
            "MZ9)JJX\n" +
            "QDD)P3W\n" +
            "X4T)13K\n" +
            "P2J)N84\n" +
            "YWG)22P\n" +
            "VJW)39N\n" +
            "14H)LPL\n" +
            "293)VQY\n" +
            "FJY)C1P\n" +
            "JMM)K4H\n" +
            "6GM)27M\n" +
            "BBM)LGD\n" +
            "ZF1)V7T\n" +
            "G41)XR2\n" +
            "JVN)FYP\n" +
            "WQ2)YQV\n" +
            "LN8)BQY\n" +
            "17R)TR1\n" +
            "4H8)W85\n" +
            "1WK)B8P\n" +
            "QPD)7Y3\n" +
            "6J8)XCD\n" +
            "21L)NZV\n" +
            "PC7)KQR\n" +
            "DL7)HK6\n" +
            "B62)NQM\n" +
            "CGM)D94\n" +
            "RLH)TT5\n" +
            "ZDK)J6L\n" +
            "32P)96X\n" +
            "T1J)5H6\n" +
            "B2D)4JB\n" +
            "VV7)6WC\n" +
            "QTM)VWR\n" +
            "ZXS)9GV\n" +
            "7ZQ)8L4\n" +
            "Z51)685\n" +
            "G71)H6M\n" +
            "JBB)37L\n" +
            "3CR)B58\n" +
            "HNC)T1P\n" +
            "89T)ZJ8\n" +
            "RBC)CFK\n" +
            "7V5)SWZ\n" +
            "5XY)54K\n" +
            "YYN)VTX\n" +
            "KYX)7KD\n" +
            "D94)LL9\n" +
            "FVH)KHD\n" +
            "B78)89G\n" +
            "8FF)NLQ\n" +
            "TQB)6V7\n" +
            "Z3Q)MD4\n" +
            "WL7)3GK\n" +
            "6K3)NWK\n" +
            "TLK)PCN\n" +
            "3M1)GMJ\n" +
            "Y79)C1G\n" +
            "RBN)52Q\n" +
            "JS8)TCF\n" +
            "VVL)XS2\n" +
            "H9M)FMB\n" +
            "Z6Y)768\n" +
            "J3G)3M1\n" +
            "M6P)XBP\n" +
            "2VL)KRD\n" +
            "439)R4S\n" +
            "5ZF)QDX\n" +
            "TK6)TNW\n" +
            "PY2)439\n" +
            "1XN)BXF\n" +
            "WS3)YWP\n" +
            "11W)SCQ\n" +
            "9HZ)JZF\n" +
            "8T4)WDD\n" +
            "SFP)XBT\n" +
            "PHL)15K\n" +
            "YSL)R36\n" +
            "F1W)CVY\n" +
            "YS6)M15\n" +
            "1SJ)RQK\n" +
            "CJ3)6GG\n" +
            "1MV)PXL\n" +
            "8W5)KBF\n" +
            "6GS)641\n" +
            "L6M)4PQ\n" +
            "WWZ)WWM\n" +
            "M4Y)3CY\n" +
            "CKM)NMG\n" +
            "C1G)Y6S\n" +
            "ZLT)QNC\n" +
            "WSB)TWV\n" +
            "H8F)D5F\n" +
            "DG3)NVD\n" +
            "RC7)6CZ\n" +
            "9Z7)X13\n" +
            "5TG)V25\n" +
            "KFB)27V\n" +
            "4HV)6JV\n" +
            "P68)TJZ\n" +
            "2SX)KCP\n" +
            "QM6)FR2\n" +
            "2Y1)H6S\n" +
            "RDF)GGB\n" +
            "XBQ)N62\n" +
            "ZMW)RNS\n" +
            "DTZ)WHM\n" +
            "F4K)VB9\n" +
            "W66)1HG\n" +
            "C1G)FJV\n" +
            "CWQ)7R5\n" +
            "61N)WS3\n" +
            "CLH)H9V\n" +
            "P3W)DD2\n" +
            "7GG)ZBZ\n" +
            "PXW)DQ8\n" +
            "GDY)2WF\n" +
            "KNS)X3Q\n" +
            "6WC)BFG\n" +
            "9MT)XH8\n" +
            "KBF)6H7\n" +
            "V97)Z4D\n" +
            "QJP)3BF\n" +
            "KWX)DPD\n" +
            "FS6)7SP\n" +
            "N3G)4WK\n" +
            "NSY)VV7\n" +
            "4V5)F79\n" +
            "11D)2SX\n" +
            "6NX)FMH\n" +
            "MQH)VYS\n" +
            "SV3)RY5\n" +
            "FJV)GLS\n" +
            "WDD)NX5\n" +
            "FT7)NRF\n" +
            "GT3)2VY\n" +
            "PW3)5LF\n" +
            "H6S)X43\n" +
            "18X)XC3\n" +
            "MJR)Y8X\n" +
            "TKM)KFK\n" +
            "Y9D)WZ7\n" +
            "9B6)GQ4\n" +
            "4HV)X2R\n" +
            "NWK)5WP\n" +
            "XGD)MXK\n" +
            "JT8)MJX\n" +
            "P8V)W1Y\n" +
            "6B1)TQB\n" +
            "J5T)PJD\n" +
            "RQQ)QCG\n" +
            "PNH)FJY\n" +
            "ZKC)8T4\n" +
            "TW9)17R\n" +
            "8L3)M4Y\n" +
            "K2H)FKT\n" +
            "N7N)YYX\n" +
            "3H4)X94\n" +
            "4CN)2TW\n" +
            "XKQ)WFS\n" +
            "R23)T9K\n" +
            "YVF)ZKC\n" +
            "BD2)QBN\n" +
            "QSK)5VG\n" +
            "DW8)V3R\n" +
            "N3Q)PPH\n" +
            "FYP)GMT\n" +
            "1P7)L6D\n" +
            "8J4)F5G\n" +
            "8Y6)RQW\n" +
            "N8V)M2J\n" +
            "ZM7)HDW\n" +
            "XG9)3YT\n" +
            "9G6)T53\n" +
            "P7G)38R\n" +
            "C9P)9D1\n" +
            "XM5)WBJ\n" +
            "FVT)ST3\n" +
            "NX5)YKP\n" +
            "8R2)4SM\n" +
            "LCL)8CT\n" +
            "WCP)5JM\n" +
            "221)J18\n" +
            "MLP)N6H\n" +
            "18X)K9N\n" +
            "393)GDS\n" +
            "182)Z3Q\n" +
            "WMY)WGJ\n" +
            "9JM)QQ6\n" +
            "FZZ)RDD\n" +
            "6YW)CDP\n" +
            "9X7)VGQ\n" +
            "PK6)41M\n" +
            "8P3)YD5\n" +
            "9SV)W3L\n" +
            "M4N)W67\n" +
            "F7Q)ZRH\n" +
            "VCS)P2J\n" +
            "QSB)T95\n" +
            "NXW)MG7\n" +
            "SS6)HNS\n" +
            "V8G)R4P\n" +
            "2DB)BVL\n" +
            "7DF)WMS\n" +
            "6QS)RGC\n" +
            "9D1)865\n" +
            "54X)JF8\n" +
            "81D)FZZ\n" +
            "172)Y9D\n" +
            "8VZ)WSB\n" +
            "GDS)M14\n" +
            "MG7)P8F\n" +
            "7RB)H1M\n" +
            "TPY)XXH\n" +
            "9L7)VVB\n" +
            "BD3)ZPM\n" +
            "369)13W\n" +
            "TRH)MD7\n" +
            "MFX)QMG\n" +
            "8KQ)FZR\n" +
            "LXP)XN5\n" +
            "BVP)H78\n" +
            "P5T)SP4\n" +
            "Z6T)4V5\n" +
            "KYX)PDV\n" +
            "NZV)1MW\n" +
            "9YR)ZKH\n" +
            "M2J)QY1\n" +
            "6V7)5T2\n" +
            "W9H)SAN\n" +
            "BZX)7RL\n" +
            "QQ6)52D\n" +
            "HBK)9KL\n" +
            "78K)XJV\n" +
            "NKZ)X7T\n" +
            "Z51)C44\n" +
            "JWR)BHQ\n" +
            "JLW)CVV\n" +
            "9RM)N8V\n" +
            "WRL)6V5\n" +
            "BBL)DGZ\n" +
            "PJD)DJP\n" +
            "RX3)KDG\n" +
            "XR9)D69\n" +
            "2Y4)YW9\n" +
            "TJN)7RC\n" +
            "CHH)SQL\n" +
            "72H)WCP\n" +
            "M14)16J\n" +
            "2N2)XM5\n" +
            "TWY)XZS\n" +
            "JD7)R9H\n" +
            "6XK)738\n" +
            "YRH)18X\n" +
            "CZW)LCL\n" +
            "K1B)ZV3\n" +
            "BQY)W1L\n" +
            "61H)ZVB\n" +
            "YYR)XG9\n" +
            "WBN)4W5\n" +
            "N62)BBL\n" +
            "5LL)KG5\n" +
            "7LX)DR3\n" +
            "KQD)C7V\n" +
            "5ZD)CW1\n" +
            "2L5)MPD\n" +
            "F8R)X6S\n" +
            "QVG)21L\n" +
            "KHD)SNC\n" +
            "7SP)N9L\n" +
            "J9S)7HS\n" +
            "8NF)2TY\n" +
            "GHJ)9SV\n" +
            "C7V)3HB\n" +
            "JKG)1P7\n" +
            "7KP)V21\n" +
            "YBL)2QV\n" +
            "HTX)TJJ\n" +
            "V7T)LXP\n" +
            "DX6)JWZ\n" +
            "RNQ)TD4\n" +
            "333)Z65\n" +
            "768)16X\n" +
            "7L5)WX7\n" +
            "6VK)1SJ\n" +
            "39N)WRL\n" +
            "R5R)RBW\n" +
            "YW1)JJG\n" +
            "SP2)2N2\n" +
            "GV9)WL6\n" +
            "P59)JGV\n" +
            "PDF)G89\n" +
            "NDD)WVY\n" +
            "2JP)MZW\n" +
            "QJP)7SS\n" +
            "WL6)VJW\n" +
            "B2N)B55\n" +
            "BBZ)H8T\n" +
            "PYS)DGY\n" +
            "BPM)HS8\n" +
            "5MR)RYC\n" +
            "FLV)K8K\n" +
            "SNG)YSL\n" +
            "ZJ8)8L3\n" +
            "WGJ)DX6\n" +
            "MNV)H27\n" +
            "7JR)NZ7\n" +
            "GLS)YJ6\n" +
            "3RC)NJ7\n" +
            "FJV)R42\n" +
            "B7D)SM5\n" +
            "WQZ)D4D\n" +
            "KKK)7L5\n" +
            "78G)K9D\n" +
            "XP9)1FP\n" +
            "ZV6)F4X\n" +
            "FGL)2Y1\n" +
            "VP8)M93\n" +
            "5SB)38X\n" +
            "RN3)N66\n" +
            "CDY)LWR\n" +
            "WMH)L6M\n" +
            "KX5)5G8\n" +
            "JWZ)W7J\n" +
            "DR3)SH6\n" +
            "5N5)5NY\n" +
            "ZHM)MBQ\n" +
            "K4H)YTY\n" +
            "4LJ)14S\n" +
            "PMB)2HK\n" +
            "MRP)C8W\n" +
            "27M)CC8\n" +
            "PDD)JYW\n" +
            "1FF)GR6\n" +
            "KXH)BZ1\n" +
            "7RC)1GQ\n" +
            "FMB)PNH\n" +
            "MJX)1V6\n" +
            "BBG)QK6\n" +
            "V25)J4B\n" +
            "PP3)PC7\n" +
            "D7B)WSV\n" +
            "3B5)PR1\n" +
            "7BD)XVB\n" +
            "N9L)8L8\n" +
            "61H)DQS\n" +
            "K9D)1V8\n" +
            "LQN)393\n" +
            "89X)BK1\n" +
            "B14)ZYZ\n" +
            "4KJ)NRK\n" +
            "ZCV)FVC\n" +
            "X6D)WQ2\n" +
            "13K)7LX\n" +
            "7Z9)RWG\n" +
            "1YB)BH3\n" +
            "6MH)3ZT\n" +
            "XR2)6B1\n" +
            "3P9)H4S\n" +
            "SBV)SHH\n" +
            "XM2)1K5\n" +
            "VB9)NMF\n" +
            "2RJ)HHB\n" +
            "89G)QDB\n" +
            "TD4)9R7\n" +
            "L21)BT7\n" +
            "9G9)LNH\n" +
            "G59)FFQ\n" +
            "SWQ)XWF\n" +
            "FBT)688\n" +
            "FFQ)JVJ\n" +
            "D7G)GHB\n" +
            "K9T)7YL\n" +
            "MKC)235\n" +
            "5JM)WD5\n" +
            "SMF)TLK\n" +
            "F31)9MT\n" +
            "8LF)BQX\n" +
            "5N2)4QW\n" +
            "2VM)R4T\n" +
            "FMK)HH2\n" +
            "W1N)Q44\n" +
            "JY1)7HB\n" +
            "8L4)B2D\n" +
            "CVL)7H5\n" +
            "SHH)GKP\n" +
            "TSG)FT7\n" +
            "WBJ)G1Z\n" +
            "HS8)5JV\n" +
            "BY5)RBM\n" +
            "LNP)PZ9\n" +
            "3BF)WD7\n" +
            "RDS)5ST\n" +
            "JYW)LD6\n" +
            "XBP)XNT\n" +
            "7HH)84T\n" +
            "93Q)1S2\n" +
            "ZV3)9RM\n" +
            "J3X)Y36\n" +
            "LD6)S1X\n" +
            "JWZ)NDD\n" +
            "TZT)8LS\n" +
            "W7W)P5T\n" +
            "K5Z)ZXS\n" +
            "WZ5)7GG\n" +
            "ZMG)QL4\n" +
            "HDW)JC1\n" +
            "GK5)NTK\n" +
            "VCS)V9L\n" +
            "VZZ)QPD\n" +
            "FL6)BZX\n" +
            "SNC)HNC\n" +
            "S6Z)Q57\n" +
            "FZC)BVS\n" +
            "S5H)GNV\n" +
            "T8B)5MQ\n" +
            "FF3)BWS\n" +
            "SCQ)PF1\n" +
            "41D)3Y2\n" +
            "Z4D)Y4K\n" +
            "FCP)DPG\n" +
            "N9L)J8S\n" +
            "H63)GXJ\n" +
            "T9K)S6Z\n" +
            "BWL)DKG\n" +
            "PZM)JRP\n" +
            "SP4)WWL\n" +
            "ZKH)PMB\n" +
            "DVC)5LL\n" +
            "LVK)QL6\n" +
            "PBD)2C2\n" +
            "Y98)8W4\n" +
            "1SZ)ZV6\n" +
            "SNC)331\n" +
            "R2C)W9H\n" +
            "KWL)NY3\n" +
            "893)221\n" +
            "DZD)32P\n" +
            "T1P)WKT\n" +
            "C1P)BCP\n" +
            "5KJ)R9B\n" +
            "YWN)369\n" +
            "FK8)9VH\n" +
            "31R)R5R\n" +
            "38X)Z6Y\n" +
            "S8Z)PY2\n" +
            "S33)RN3\n" +
            "16J)D28\n" +
            "JRP)T8B\n" +
            "77D)1XW\n" +
            "K4H)3BZ\n" +
            "DWN)GX8\n" +
            "QBF)WXV\n" +
            "31J)7BL\n" +
            "Y2W)D82\n" +
            "WTF)Q78\n" +
            "VTX)5LY\n" +
            "75H)WWZ\n" +
            "9VH)YW1\n" +
            "S54)XKQ\n" +
            "BZ1)7DJ\n" +
            "DGZ)7XM\n" +
            "MXQ)B15\n" +
            "HH2)1KQ\n" +
            "N86)QX7\n" +
            "FPR)ZDK\n" +
            "2C2)HX4\n" +
            "YYX)Z3S\n" +
            "GMP)XM2\n" +
            "F56)C3S\n" +
            "3YG)ZGD\n" +
            "7YS)HNZ\n" +
            "B2D)6YV\n" +
            "R36)S8M";

    class Node {
        String value;
        int orbits;
        List<Node> children = new ArrayList<>();

        public String getValue() {
            return value;
        }

        public void setValue(String value) {
            this.value = value;
        }

        public int getOrbits() {
            return orbits;
        }

        public void setOrbits(int orbits) {
            this.orbits = orbits;
        }

        public List<Node> getChildren() {
            return children;
        }

        public void setChildren(List<Node> children) {
            this.children = children;
        }
    }
}
