package advent2022;

import org.junit.Test;

public class Day2Test {

    enum Hands {
        X(1), Y(2), Z(3), A(1), B(2), C(3);

        int score;
        Hands beats, loses, draws;

        static {
            A.beats=Z;
            A.loses=Y;
            A.draws=X;

            B.beats=X;
            B.loses=Z;
            B.draws=Y;

            C.beats=Y;
            C.loses=X;
            C.draws=Z;
        }

        Hands(int score) {
            this.score = score;
        }

    }

    @Test
    public void test() {
        String[] rounds = getStringArrayOfHands(input);
        int score = 0;
        int score2 = 0;
        for (String round : rounds) {
            Hands opp = Hands.valueOf(round.split(" ")[0]);
            Hands me = Hands.valueOf(round.split(" ")[1]);
            Hands dir = Hands.valueOf(round.split(" ")[1]);
            score+=me.score;
            if (opp.beats==me) {
                score+=0;
            } else if (opp.draws==me) {
                score+=3;
            } else {
                score+=6;
            }

            if (dir==Hands.X) {
                score2+=opp.beats.score;
            } else if (dir==Hands.Y) {
                score2+=3;
                score2+=opp.draws.score;
            } else {
                score2+=6;
                score2+=opp.loses.score;
            }

        }
        System.out.println(score);
        System.out.println(score2);
    }

    public static String[] getStringArrayOfHands(String input) {
        return input.split("\n");
    }

    private String input = "C X\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "B X\n" +
            "B Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "B Y\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "C Z\n" +
            "A X\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "C X\n" +
            "B Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "A Y\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "B Y\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "A Y\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "B Y\n" +
            "C Z\n" +
            "C X\n" +
            "A Y\n" +
            "A Z\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "A Y\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "A Y\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A Y\n" +
            "C X\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "A Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "B Y\n" +
            "B Y\n" +
            "A Y\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "A Y\n" +
            "A Y\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "B Y\n" +
            "A Y\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "A Y\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "B Y\n" +
            "B X\n" +
            "B Y\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "A Y\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "A Y\n" +
            "B X\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "A X\n" +
            "B X\n" +
            "A X\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "B Y\n" +
            "A Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "A Y\n" +
            "B Y\n" +
            "C Z\n" +
            "A Y\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "A Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "A X\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "A Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "B Z\n" +
            "B X\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "A Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "C X\n" +
            "B Y\n" +
            "A Z\n" +
            "A Y\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "A Y\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "A Y\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C Y\n" +
            "A Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "B Y\n" +
            "A Y\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "A Y\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "A Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "A Y\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B X\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "B X\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "B Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "A Y\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "B X\n" +
            "A Y\n" +
            "B Y\n" +
            "A Z\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "C Z\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "B Y\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "A Z\n" +
            "A X\n" +
            "A Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "A X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "B Y\n" +
            "A X\n" +
            "B Y\n" +
            "A Z\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "A X\n" +
            "B Y\n" +
            "B Y\n" +
            "A Z\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "C Z\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "A Y\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "C Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "C X\n" +
            "C Y\n" +
            "A Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "A Y\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "A Y\n" +
            "A Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "A Y\n" +
            "B Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "A Y\n" +
            "B Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "B Y\n" +
            "C Y\n" +
            "B X\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "B Y\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "B Y\n" +
            "B Y\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "B Y\n" +
            "B Y\n" +
            "B X\n" +
            "A Y\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C Z\n" +
            "B Y\n" +
            "B Y\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "B Y\n" +
            "B Y\n" +
            "A Z\n" +
            "B Y\n" +
            "B Y\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "B Y\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "A Z\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C X\n" +
            "C Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Z\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "B X\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "B Y\n" +
            "A Y\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Y\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "A Y\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "A Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "B X\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "A Y\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Y\n" +
            "B Y\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "B Y\n" +
            "A Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "B X\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "A Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "B Y\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "A Y\n" +
            "B Y\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "B Y\n" +
            "C Z\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Y\n" +
            "A X\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C X\n" +
            "A Y\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "A X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "A Y\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "B Z\n" +
            "B X\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "A Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C Z\n" +
            "A Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "C Z\n" +
            "A Z\n" +
            "A Y\n" +
            "C X\n" +
            "A Y\n" +
            "B Y\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "A Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "B Y\n" +
            "C Z\n" +
            "B X\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "A Z\n" +
            "B Y\n" +
            "B Y\n" +
            "A Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "A Y\n" +
            "A Z\n" +
            "A X\n" +
            "C Z\n" +
            "B Y\n" +
            "B Y\n" +
            "B X\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "A Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "A Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "B X\n" +
            "C Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "B X\n" +
            "A Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "B Y\n" +
            "C X\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "B X\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "A Y\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "B Y\n" +
            "B Y\n" +
            "A Y\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "A Y\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "B Y\n" +
            "B Y\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "B X\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C Y\n" +
            "A Y\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "B Y\n" +
            "B Z\n" +
            "B Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C Z\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "C Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "B X\n" +
            "A Y\n" +
            "C Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "C Z\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "A Y\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C X\n" +
            "A Z\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "B Y\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B Z\n" +
            "A Y\n" +
            "A Y\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "B Y\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B Y\n" +
            "B Y\n" +
            "A Y\n" +
            "B Y\n" +
            "B Z\n" +
            "B X\n" +
            "C X\n" +
            "B Y\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "A Y\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "B Y\n" +
            "B Y\n" +
            "B Y\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "A Y\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "B Y\n" +
            "C Y\n" +
            "B Y\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Y\n" +
            "B X\n" +
            "A X\n" +
            "B Y\n" +
            "A Z\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "B Y\n" +
            "C Z\n" +
            "A Y\n" +
            "B Z\n" +
            "C Y\n" +
            "A Y\n" +
            "B Y\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "B X\n" +
            "A Z\n" +
            "B Z\n" +
            "A X\n" +
            "B X\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Y\n" +
            "A Y\n" +
            "C Z\n" +
            "A X\n" +
            "B Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Y\n" +
            "A Y\n" +
            "B Y\n" +
            "C Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "B X\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "C Z\n" +
            "B Y\n" +
            "C X\n" +
            "B Y\n" +
            "B Y\n" +
            "A X\n" +
            "C X\n" +
            "B Y\n" +
            "B X\n" +
            "C Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A Y\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "A Z\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "A Z\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "B X\n" +
            "C X\n" +
            "C Z\n" +
            "B Y\n" +
            "A Y\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "A Z\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "B Y\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "B Y\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B X\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "B Y\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "C X\n" +
            "B Y\n" +
            "B X\n" +
            "A Y\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "A Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "B Y\n" +
            "B Y\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B X\n" +
            "B Y\n" +
            "B X\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "A Y\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "B Y\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "B Y\n" +
            "B Y\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Y\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "B Y\n" +
            "B X\n" +
            "A Z\n" +
            "C Z\n" +
            "C X\n" +
            "B X\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "A Z\n" +
            "C X\n" +
            "A Y\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "B Y\n" +
            "A X\n" +
            "B Z\n" +
            "B Y\n" +
            "B X\n" +
            "A Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Y\n" +
            "B X\n" +
            "C X\n" +
            "B Y\n" +
            "C Y\n" +
            "A Y\n" +
            "B Y\n" +
            "B Y\n" +
            "B Z\n" +
            "B Y\n" +
            "B X\n" +
            "A Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Z\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "C X\n" +
            "A Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "A Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "B Y\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "C X\n" +
            "A Y\n" +
            "C X\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "B Y\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "A Y\n" +
            "B X\n" +
            "A X\n" +
            "A Z\n" +
            "A Y\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "B X\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "A Z\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "B X\n" +
            "B Y\n" +
            "B Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "C Y";

}
